package com.mrcrayfish.furniture.util;

import com.mrcrayfish.furniture.Reference;

/**
 * Author: MrCrayfish
 */
public class BlockNames
{
    public static final String TABLE_OAK = Reference.MOD_ID + ":oak_table";
    public static final String TABLE_SPRUCE = Reference.MOD_ID + ":spruce_table";
    public static final String TABLE_BIRCH = Reference.MOD_ID + ":birch_table";
    public static final String TABLE_JUNGLE = Reference.MOD_ID + ":jungle_table";
    public static final String TABLE_ACACIA = Reference.MOD_ID + ":acacia_table";
    public static final String TABLE_DARK_OAK = Reference.MOD_ID + ":dark_oak_table";
    public static final String TABLE_STONE = Reference.MOD_ID + ":stone_table";
    public static final String TABLE_GRANITE = Reference.MOD_ID + ":granite_table";
    public static final String TABLE_DIORITE = Reference.MOD_ID + ":diorite_table";
    public static final String TABLE_ANDESITE = Reference.MOD_ID + ":andesite_table";
    public static final String TABLE_STRIPPED_OAK = Reference.MOD_ID + ":stripped_oak_table";
    public static final String TABLE_STRIPPED_SPRUCE = Reference.MOD_ID + ":stripped_spruce_table";
    public static final String TABLE_STRIPPED_BIRCH = Reference.MOD_ID + ":stripped_birch_table";
    public static final String TABLE_STRIPPED_JUNGLE = Reference.MOD_ID + ":stripped_jungle_table";
    public static final String TABLE_STRIPPED_ACACIA = Reference.MOD_ID + ":stripped_acacia_table";
    public static final String TABLE_STRIPPED_DARK_OAK = Reference.MOD_ID + ":stripped_dark_oak_table";
    public static final String CHAIR_OAK = Reference.MOD_ID + ":oak_chair";
    public static final String CHAIR_SPRUCE = Reference.MOD_ID + ":spruce_chair";
    public static final String CHAIR_BIRCH = Reference.MOD_ID + ":birch_chair";
    public static final String CHAIR_JUNGLE = Reference.MOD_ID + ":jungle_chair";
    public static final String CHAIR_ACACIA = Reference.MOD_ID + ":acacia_chair";
    public static final String CHAIR_DARK_OAK = Reference.MOD_ID + ":dark_oak_chair";
    public static final String CHAIR_STONE = Reference.MOD_ID + ":stone_chair";
    public static final String CHAIR_GRANITE = Reference.MOD_ID + ":granite_chair";
    public static final String CHAIR_DIORITE = Reference.MOD_ID + ":diorite_chair";
    public static final String CHAIR_ANDESITE = Reference.MOD_ID + ":andesite_chair";
    public static final String CHAIR_STRIPPED_OAK = Reference.MOD_ID + ":stripped_oak_chair";
    public static final String CHAIR_STRIPPED_SPRUCE = Reference.MOD_ID + ":stripped_spruce_chair";
    public static final String CHAIR_STRIPPED_BIRCH = Reference.MOD_ID + ":stripped_birch_chair";
    public static final String CHAIR_STRIPPED_JUNGLE = Reference.MOD_ID + ":stripped_jungle_chair";
    public static final String CHAIR_STRIPPED_ACACIA = Reference.MOD_ID + ":stripped_acacia_chair";
    public static final String CHAIR_STRIPPED_DARK_OAK = Reference.MOD_ID + ":stripped_dark_oak_chair";
    public static final String COFFEE_TABLE_OAK = Reference.MOD_ID + ":oak_coffee_table";
    public static final String COFFEE_TABLE_SPRUCE = Reference.MOD_ID + ":spruce_coffee_table";
    public static final String COFFEE_TABLE_BIRCH = Reference.MOD_ID + ":birch_coffee_table";
    public static final String COFFEE_TABLE_JUNGLE = Reference.MOD_ID + ":jungle_coffee_table";
    public static final String COFFEE_TABLE_ACACIA = Reference.MOD_ID + ":acacia_coffee_table";
    public static final String COFFEE_TABLE_DARK_OAK = Reference.MOD_ID + ":dark_oak_coffee_table";
    public static final String COFFEE_TABLE_STONE = Reference.MOD_ID + ":stone_coffee_table";
    public static final String COFFEE_TABLE_GRANITE = Reference.MOD_ID + ":granite_coffee_table";
    public static final String COFFEE_TABLE_DIORITE = Reference.MOD_ID + ":diorite_coffee_table";
    public static final String COFFEE_TABLE_ANDESITE = Reference.MOD_ID + ":andesite_coffee_table";
    public static final String COFFEE_TABLE_STRIPPED_OAK = Reference.MOD_ID + ":stripped_oak_coffee_table";
    public static final String COFFEE_TABLE_STRIPPED_SPRUCE = Reference.MOD_ID + ":stripped_spruce_coffee_table";
    public static final String COFFEE_TABLE_STRIPPED_BIRCH = Reference.MOD_ID + ":stripped_birch_coffee_table";
    public static final String COFFEE_TABLE_STRIPPED_JUNGLE = Reference.MOD_ID + ":stripped_jungle_coffee_table";
    public static final String COFFEE_TABLE_STRIPPED_ACACIA = Reference.MOD_ID + ":stripped_acacia_coffee_table";
    public static final String COFFEE_TABLE_STRIPPED_DARK_OAK = Reference.MOD_ID + ":stripped_dark_oak_coffee_table";
    
    public static final String FREEZER = Reference.MOD_ID + ":freezer";
    public static final String FRIDGE = Reference.MOD_ID + ":fridge";
    public static final String CABINET_OAK = Reference.MOD_ID + ":cabinet_oak";
    public static final String CABINET_SPRUCE = Reference.MOD_ID + ":cabinet_spruce";
    public static final String CABINET_BIRCH = Reference.MOD_ID + ":cabinet_birch";
    public static final String CABINET_JUNGLE = Reference.MOD_ID + ":cabinet_jungle";
    public static final String CABINET_ACACIA = Reference.MOD_ID + ":cabinet_acacia";
    public static final String CABINET_DARK_OAK = Reference.MOD_ID + ":cabinet_dark_oak";
    public static final String CABINET_STONE = Reference.MOD_ID + ":cabinet_stone";
    public static final String CABINET_GRANITE = Reference.MOD_ID + ":cabinet_granite";
    public static final String CABINET_DIORITE = Reference.MOD_ID + ":cabinet_diorite";
    public static final String CABINET_ANDESITE = Reference.MOD_ID + ":cabinet_andesite";
    public static final String BEDSIDE_CABINET_OAK = Reference.MOD_ID + ":bedside_cabinet_oak";
    public static final String BEDSIDE_CABINET_SPRUCE = Reference.MOD_ID + ":bedside_cabinet_spruce";
    public static final String BEDSIDE_CABINET_BIRCH = Reference.MOD_ID + ":bedside_cabinet_birch";
    public static final String BEDSIDE_CABINET_JUNGLE = Reference.MOD_ID + ":bedside_cabinet_jungle";
    public static final String BEDSIDE_CABINET_ACACIA = Reference.MOD_ID + ":bedside_cabinet_acacia";
    public static final String BEDSIDE_CABINET_DARK_OAK = Reference.MOD_ID + ":bedside_cabinet_dark_oak";
    public static final String BEDSIDE_CABINET_STONE = Reference.MOD_ID + ":bedside_cabinet_stone";
    public static final String BEDSIDE_CABINET_GRANITE = Reference.MOD_ID + ":bedside_cabinet_granite";
    public static final String BEDSIDE_CABINET_DIORITE = Reference.MOD_ID + ":bedside_cabinet_diorite";
    public static final String BEDSIDE_CABINET_ANDESITE = Reference.MOD_ID + ":bedside_cabinet_andesite";
    public static final String BLINDS_OAK = Reference.MOD_ID + ":blinds_oak";
    public static final String BLINDS_SPRUCE = Reference.MOD_ID + ":blinds_spruce";
    public static final String BLINDS_BIRCH = Reference.MOD_ID + ":blinds_birch";
    public static final String BLINDS_JUNGLE = Reference.MOD_ID + ":blinds_jungle";
    public static final String BLINDS_ACACIA = Reference.MOD_ID + ":blinds_acacia";
    public static final String BLINDS_DARK_OAK = Reference.MOD_ID + ":blinds_dark_oak";
    public static final String SOFA_WHITE = Reference.MOD_ID + ":sofa_white";
    public static final String SOFA_ORANGE = Reference.MOD_ID + ":sofa_orange";
    public static final String SOFA_MAGENTA = Reference.MOD_ID + ":sofa_magenta";
    public static final String SOFA_LIGHT_BLUE = Reference.MOD_ID + ":sofa_light_blue";
    public static final String SOFA_YELLOW = Reference.MOD_ID + ":sofa_yellow";
    public static final String SOFA_LIME = Reference.MOD_ID + ":sofa_lime";
    public static final String SOFA_PINK = Reference.MOD_ID + ":sofa_pink";
    public static final String SOFA_GRAY = Reference.MOD_ID + ":sofa_gray";
    public static final String SOFA_LIGHT_GRAY = Reference.MOD_ID + ":sofa_light_gray";
    public static final String SOFA_CYAN = Reference.MOD_ID + ":sofa_cyan";
    public static final String SOFA_PURPLE = Reference.MOD_ID + ":sofa_purple";
    public static final String SOFA_BLUE = Reference.MOD_ID + ":sofa_blue";
    public static final String SOFA_BROWN = Reference.MOD_ID + ":sofa_brown";
    public static final String SOFA_GREEN = Reference.MOD_ID + ":sofa_green";
    public static final String SOFA_RED = Reference.MOD_ID + ":sofa_red";
    public static final String SOFA_BLACK = Reference.MOD_ID + ":sofa_black";
    public static final String SOFA_JEB = Reference.MOD_ID + ":sofa_jeb";
    public static final String CURTAIN_WHITE = Reference.MOD_ID + ":curtain_white";
    public static final String CURTAIN_ORANGE = Reference.MOD_ID + ":curtain_orange";
    public static final String CURTAIN_MAGENTA = Reference.MOD_ID + ":curtain_magenta";
    public static final String CURTAIN_LIGHT_BLUE = Reference.MOD_ID + ":curtain_light_blue";
    public static final String CURTAIN_YELLOW = Reference.MOD_ID + ":curtain_yellow";
    public static final String CURTAIN_LIME = Reference.MOD_ID + ":curtain_lime";
    public static final String CURTAIN_PINK = Reference.MOD_ID + ":curtain_pink";
    public static final String CURTAIN_GRAY = Reference.MOD_ID + ":curtain_gray";
    public static final String CURTAIN_LIGHT_GRAY = Reference.MOD_ID + ":curtain_light_gray";
    public static final String CURTAIN_CYAN = Reference.MOD_ID + ":curtain_cyan";
    public static final String CURTAIN_PURPLE = Reference.MOD_ID + ":curtain_purple";
    public static final String CURTAIN_BLUE = Reference.MOD_ID + ":curtain_blue";
    public static final String CURTAIN_BROWN = Reference.MOD_ID + ":curtain_brown";
    public static final String CURTAIN_GREEN = Reference.MOD_ID + ":curtain_green";
    public static final String CURTAIN_RED = Reference.MOD_ID + ":curtain_red";
    public static final String CURTAIN_BLACK = Reference.MOD_ID + ":curtain_black";

    //TODO might not need these
    /*public static final String CURTAIN_CLOSED_WHITE = Reference.MOD_ID + ":curtain_closed_white";
    public static final String CURTAIN_CLOSED_ORANGE = Reference.MOD_ID + ":curtain_closed_orange";
    public static final String CURTAIN_CLOSED_MAGENTA = Reference.MOD_ID + ":curtain_closed_magenta";
    public static final String CURTAIN_CLOSED_LIGHT_BLUE = Reference.MOD_ID + ":curtain_closed_light_blue";
    public static final String CURTAIN_CLOSED_YELLOW = Reference.MOD_ID + ":curtain_closed_yellow";
    public static final String CURTAIN_CLOSED_LIME = Reference.MOD_ID + ":curtain_closed_lime";
    public static final String CURTAIN_CLOSED_PINK = Reference.MOD_ID + ":curtain_closed_pink";
    public static final String CURTAIN_CLOSED_GRAY = Reference.MOD_ID + ":curtain_closed_gray";
    public static final String CURTAIN_CLOSED_LIGHT_GRAY = Reference.MOD_ID + ":curtain_closed_light_gray";
    public static final String CURTAIN_CLOSED_CYAN = Reference.MOD_ID + ":curtain_closed_cyan";
    public static final String CURTAIN_CLOSED_PURPLE = Reference.MOD_ID + ":curtain_closed_purple";
    public static final String CURTAIN_CLOSED_BLUE = Reference.MOD_ID + ":curtain_closed_blue";
    public static final String CURTAIN_CLOSED_BROWN = Reference.MOD_ID + ":curtain_closed_brown";
    public static final String CURTAIN_CLOSED_GREEN = Reference.MOD_ID + ":curtain_closed_green";
    public static final String CURTAIN_CLOSED_RED = Reference.MOD_ID + ":curtain_closed_red";
    public static final String CURTAIN_CLOSED_BLACK = Reference.MOD_ID + ":curtain_closed_black";*/

    /* Electronic Update */
    public static final String TV = Reference.MOD_ID + ":tv";
    public static final String COMPUTER = Reference.MOD_ID + ":computer";
    public static final String PRINTER = Reference.MOD_ID + ":printer";
    public static final String ELECTRIC_FENCE = Reference.MOD_ID + ":electric_fence";
    public static final String DOOR_BELL = Reference.MOD_ID + ":door_bell";
    public static final String STEREO = Reference.MOD_ID + ":stereo";
    public static final String FIRE_ALARM_OFF = Reference.MOD_ID + ":fire_alarm_off";
    public static final String FIRE_ALARM_ON = Reference.MOD_ID + ":fire_alarm_on";
    public static final String CEILING_LIGHT_OFF = Reference.MOD_ID + ":ceiling_light_off";
    public static final String CEILING_LIGHT_ON = Reference.MOD_ID + ":ceiling_light_on";
    public static final String LAMP_ON = Reference.MOD_ID + ":lamp_on";
    public static final String LAMP_OFF = Reference.MOD_ID + ":lamp_off";

    /* Bathroom */
    public static final String TOILET = Reference.MOD_ID + ":toilet";
    public static final String BASIN = Reference.MOD_ID + ":basin";
    public static final String BATH = Reference.MOD_ID + ":bath";
    public static final String SHOWER_BOTTOM = Reference.MOD_ID + ":shower_bottom";
    public static final String SHOWER_TOP = Reference.MOD_ID + ":shower_top";
    public static final String SHOWER_HEAD_OFF = Reference.MOD_ID + ":shower_head_off";
    public static final String SHOWER_HEAD_ON = Reference.MOD_ID + ":shower_head_on";
    public static final String WALL_CABINET = Reference.MOD_ID + ":wall_cabinet";
    public static final String MIRROR = Reference.MOD_ID + ":mirror";
    public static final String BIN = Reference.MOD_ID + ":bin";

    /* Kitchen */
    public static final String OVEN = Reference.MOD_ID + ":oven";
    public static final String RANGE_HOOD = Reference.MOD_ID + ":range_hood";
    public static final String RANGE_HOOD_POWERED = Reference.MOD_ID + ":range_hood_powered";
    public static final String TOASTER = Reference.MOD_ID + ":toaster";
    public static final String MICROWAVE = Reference.MOD_ID + ":microwave";
    public static final String BLENDER = Reference.MOD_ID + ":blender";
    public static final String WASHING_MACHINE = Reference.MOD_ID + ":washing_machine";
    public static final String DISHWASHER = Reference.MOD_ID + ":dishwasher";
    public static final String COUNTER = Reference.MOD_ID + ":counter"; //TODO flatten?
    public static final String COUNTER_SINK = Reference.MOD_ID + ":counter_sink"; //TODO flatten?
    public static final String KITCHEN_CABINET = Reference.MOD_ID + ":kitchen_cabinet"; //TODO flatten?
    public static final String CUP = Reference.MOD_ID + ":cup";
    public static final String PLATE = Reference.MOD_ID + ":plate";
    public static final String COOKIE_JAR = Reference.MOD_ID + ":cookie_jar";
    public static final String BAR_STOOL = Reference.MOD_ID + ":bar_stool";
    public static final String CHOPPING_BOARD = Reference.MOD_ID + ":chopping_board";
    public static final String PRESENT = Reference.MOD_ID + ":present"; //TODO flatten?
    public static final String TREE_BOTTOM = Reference.MOD_ID + ":tree_bottom";
    public static final String TREE_TOP = Reference.MOD_ID + ":tree_top";
    public static final String MANTEL_PIECE = Reference.MOD_ID + ":mantel_piece";
    public static final String GRAND_CHAIR_TOP = Reference.MOD_ID + ":grand_chair_top";
    public static final String GRAND_CHAIR_BOTTOM = Reference.MOD_ID + ":grand_chair_bottom";
    public static final String CANDLE = Reference.MOD_ID + ":candle";
    public static final String CHIMNEY = Reference.MOD_ID + ":chimney";
    public static final String WREATH = Reference.MOD_ID + ":wreath";
    public static final String FAIRY_LIGHT = Reference.MOD_ID + ":fairy_light";
    public static final String FIRE_PIT_OFF = Reference.MOD_ID + ":fire_pit_off";
    public static final String FIRE_PIT_ON = Reference.MOD_ID + ":fire_pit_on";
    public static final String MODERN_WINDOW = Reference.MOD_ID + ":modern_window";
    public static final String MODERN_SLIDING_DOOR = Reference.MOD_ID + ":modern_sliding_door";
    public static final String MODERN_TV = Reference.MOD_ID + ":modern_tv";
    public static final String MODERN_COUCH = Reference.MOD_ID + ":modern_couch";
    public static final String MODERN_TABLE = Reference.MOD_ID + ":modern_table";
    public static final String MODERN_CHAIR = Reference.MOD_ID + ":modern_chair";
    public static final String MODERN_BED_TOP = Reference.MOD_ID + ":modern_bed_top";
    public static final String MODERN_BED_BOTTOM = Reference.MOD_ID + ":modern_bed_bottom";
    public static final String MODERN_COFFEE_TABLE = Reference.MOD_ID + ":modern_coffee_table";
    public static final String MODERN_STAIRS = Reference.MOD_ID + ":modern_stairs";
    public static final String MODERN_TABLE_OUTDOOR = Reference.MOD_ID + ":modern_table_outdoor";
    public static final String LIGHT_SWITCH_OFF = Reference.MOD_ID + ":light_switch_off";
    public static final String LIGHT_SWITCH_ON = Reference.MOD_ID + ":light_switch_on";
    public static final String MODERN_LIGHT_OFF = Reference.MOD_ID + ":modern_light_off";
    public static final String MODERN_LIGHT_ON = Reference.MOD_ID + ":modern_light_on";
    public static final String CEILING_FAN = Reference.MOD_ID + ":ceiling_fan";
    public static final String DESK_OAK = Reference.MOD_ID + ":desk_oak";
    public static final String DESK_SPRUCE = Reference.MOD_ID + ":desk_spruce";
    public static final String DESK_BIRCH = Reference.MOD_ID + ":desk_birch";
    public static final String DESK_JUNGLE = Reference.MOD_ID + ":desk_jungle";
    public static final String DESK_ACACIA = Reference.MOD_ID + ":desk_acacia";
    public static final String DESK_DARK_OAK = Reference.MOD_ID + ":desk_dark_oak";
    public static final String DESK_STONE = Reference.MOD_ID + ":desk_stone";
    public static final String DESK_GRANITE = Reference.MOD_ID + ":desk_granite";
    public static final String DESK_DIORITE = Reference.MOD_ID + ":desk_diorite";
    public static final String DESK_ANDESITE = Reference.MOD_ID + ":desk_andesite";
    public static final String DESK_CABINET_OAK = Reference.MOD_ID + ":desk_cabinet_oak";
    public static final String DESK_CABINET_SPRUCE = Reference.MOD_ID + ":desk_cabinet_spruce";
    public static final String DESK_CABINET_BIRCH = Reference.MOD_ID + ":desk_cabinet_birch";
    public static final String DESK_CABINET_JUNGLE = Reference.MOD_ID + ":desk_cabinet_jungle";
    public static final String DESK_CABINET_ACACIA = Reference.MOD_ID + ":desk_cabinet_acacia";
    public static final String DESK_CABINET_DARK_OAK = Reference.MOD_ID + ":desk_cabinet_dark_oak";
    public static final String DESK_CABINET_STONE = Reference.MOD_ID + ":desk_cabinet_stone";
    public static final String DESK_CABINET_GRANITE = Reference.MOD_ID + ":desk_cabinet_granite";
    public static final String DESK_CABINET_DIORITE = Reference.MOD_ID + ":desk_cabinet_diorite";
    public static final String DESK_CABINET_ANDESITE = Reference.MOD_ID + ":desk_cabinet_andesite";
    public static final String DIGITAL_CLOCK = Reference.MOD_ID + ":digital_clock"; //TODO flatten
    public static final String COUNTER_DRAWER = Reference.MOD_ID + ":counter_drawer";
    public static final String DOOR_BELL_SPRUCE = Reference.MOD_ID + ":door_bell_spruce";
    public static final String DOOR_BELL_BIRCH = Reference.MOD_ID + ":door_bell_birch";
    public static final String DOOR_BELL_JUNGLE = Reference.MOD_ID + ":door_bell_jungle";
    public static final String DOOR_BELL_ACACIA = Reference.MOD_ID + ":door_bell_acacia";
    public static final String DOOR_BELL_DARK_OAK = Reference.MOD_ID + ":door_bell_dark_oak";
    public static final String PHOTO_FRAME = Reference.MOD_ID + ":photo_frame"; //TODO flatten
    public static final String CRATE_SPRUCE = Reference.MOD_ID + ":crate_spruce";
    public static final String CRATE_BIRCH = Reference.MOD_ID + ":crate_birch";
    public static final String CRATE_JUNGLE = Reference.MOD_ID + ":crate_jungle";
    public static final String CRATE_ACACIA = Reference.MOD_ID + ":crate_acacia";
    public static final String CRATE_DARK_OAK = Reference.MOD_ID + ":crate_dark_oak";
    public static final String TV_STAND = Reference.MOD_ID + ":tv_stand";

    /* Outdoor */
    public static final String TRAMPOLINE = Reference.MOD_ID + ":trampoline"; //TODO Make every colour
    public static final String CRATE = Reference.MOD_ID + ":crate";
    public static final String BENCH = Reference.MOD_ID + ":bench";
    public static final String TABLE_OUTDOOR = Reference.MOD_ID + ":table_outdoor";
    public static final String GRILL = Reference.MOD_ID + ":grill"; //TODO Make every colour
    public static final String DIVING_BOARD_BASE = Reference.MOD_ID + ":diving_board_base";
    public static final String DIVING_BOARD_PLANK = Reference.MOD_ID + ":diving_board_plank";
    public static final String DOOR_MAT = Reference.MOD_ID + ":door_mat"; //TODO flatten
    public static final String COOLER = Reference.MOD_ID + ":cooler"; //TODO flatten
    public static final String BIRD_BATH = Reference.MOD_ID + ":bird_bath";
    public static final String ROCK_PATH = Reference.MOD_ID + ":rock_path";
    public static final String PICKET_FENCE = Reference.MOD_ID + ":picket_fence";
    public static final String OUTDOOR_TAP = Reference.MOD_ID + ":outdoor_tap";
    public static final String MAIL_BOX_OAK = Reference.MOD_ID + ":mail_box_oak";
    public static final String MAIL_BOX_SPRUCE = Reference.MOD_ID + ":mail_box_spruce";
    public static final String MAIL_BOX_BIRCH = Reference.MOD_ID + ":mail_box_birch";
    public static final String MAIL_BOX_JUNGLE = Reference.MOD_ID + ":mail_box_jungle";
    public static final String MAIL_BOX_ACACIA = Reference.MOD_ID + ":mail_box_acacia";
    public static final String MAIL_BOX_DARK_OAK = Reference.MOD_ID + ":mail_box_dark_oak";
    public static final String HEDGE_OAK = Reference.MOD_ID + ":hedge_oak";
    public static final String HEDGE_SPRUCE = Reference.MOD_ID + ":hedge_spruce";
    public static final String HEDGE_BIRCH = Reference.MOD_ID + ":hedge_birch";
    public static final String HEDGE_JUNGLE = Reference.MOD_ID + ":hedge_jungle";
    public static final String HEDGE_ACACIA = Reference.MOD_ID + ":hedge_acacia";
    public static final String HEDGE_DARK_OAK = Reference.MOD_ID + ":hedge_dark_oak";
    public static final String OAK_FENCE_UPGRADED = Reference.MOD_ID + ":oak_fence_upgraded";
    public static final String SPRUCE_FENCE_UPGRADED = Reference.MOD_ID + ":spruce_fence_upgraded";
    public static final String BIRCH_FENCE_UPGRADED = Reference.MOD_ID + ":birch_fence_upgraded";
    public static final String JUNGLE_FENCE_UPGRADED = Reference.MOD_ID + ":jungle_fence_upgraded";
    public static final String ACACIA_FENCE_UPGRADED = Reference.MOD_ID + ":acacia_fence_upgraded";
    public static final String DARK_OAK_FENCE_UPGRADED = Reference.MOD_ID + ":dark_oak_fence_upgraded";
    public static final String NETHER_BRICK_FENCE_UPGRADED = Reference.MOD_ID + ":nether_brick_fence_upgraded";
    public static final String OAK_GATE_UPGRADED = Reference.MOD_ID + ":oak_gate_upgraded";
    public static final String SPRUCE_GATE_UPGRADED = Reference.MOD_ID + ":spruce_gate_upgraded";
    public static final String BIRCH_GATE_UPGRADED = Reference.MOD_ID + ":birch_gate_upgraded";
    public static final String JUNGLE_GATE_UPGRADED = Reference.MOD_ID + ":jungle_gate_upgraded";
    public static final String ACACIA_GATE_UPGRADED = Reference.MOD_ID + ":acacia_gate_upgraded";
    public static final String DARK_OAK_GATE_UPGRADED = Reference.MOD_ID + ":dark_oak_gate_upgraded";
    public static final String WHITE_GATE = Reference.MOD_ID + ":white_gate";
    public static final String OAK_PARK_BENCH = Reference.MOD_ID + ":oak_park_bench";
    public static final String SPRUCE_PARK_BENCH = Reference.MOD_ID + ":spruce_park_bench";
    public static final String BIRCH_PARK_BENCH = Reference.MOD_ID + ":birch_park_bench";
    public static final String JUNGLE_PARK_BENCH = Reference.MOD_ID + ":jungle_park_bench";
    public static final String ACACIA_PARK_BENCH = Reference.MOD_ID + ":acacia_park_bench";
    public static final String DARK_OAK_PARK_BENCH = Reference.MOD_ID + ":dark_oak_park_bench";
}
