package com.mrcrayfish.furniture.datagen;

import com.mrcrayfish.furniture.Reference;
import com.mrcrayfish.furniture.common.ModTags;
import com.mrcrayfish.furniture.core.ModBlocks;
import com.mrcrayfish.furniture.core.ModItems;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.tags.BlockTagsProvider;
import net.minecraft.data.tags.ItemTagsProvider;
import net.minecraftforge.common.data.ExistingFileHelper;

/**
 * @author Ocelot
 */
public class ItemTagGen extends ItemTagsProvider
{
    public ItemTagGen(DataGenerator generator, BlockTagsProvider blockTagsProvider, ExistingFileHelper existingFileHelper)
    {
        super(generator, blockTagsProvider, Reference.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags()
    {
        this.tag(ModTags.Items.BEDROOM)
                // Cabinets
                .add(ModBlocks.BEDSIDE_CABINET_OAK.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_SPRUCE.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_BIRCH.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_JUNGLE.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_ACACIA.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_DARK_OAK.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STONE.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_GRANITE.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_DIORITE.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_ANDESITE.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STRIPPED_DARK_OAK.get().asItem())
                // Desks
                .add(ModBlocks.DESK_OAK.get().asItem())
                .add(ModBlocks.DESK_SPRUCE.get().asItem())
                .add(ModBlocks.DESK_BIRCH.get().asItem())
                .add(ModBlocks.DESK_JUNGLE.get().asItem())
                .add(ModBlocks.DESK_ACACIA.get().asItem())
                .add(ModBlocks.DESK_DARK_OAK.get().asItem())
                .add(ModBlocks.DESK_STONE.get().asItem())
                .add(ModBlocks.DESK_GRANITE.get().asItem())
                .add(ModBlocks.DESK_DIORITE.get().asItem())
                .add(ModBlocks.DESK_ANDESITE.get().asItem())
                .add(ModBlocks.DESK_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.DESK_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.DESK_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.DESK_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.DESK_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.DESK_STRIPPED_DARK_OAK.get().asItem())
                // Desk Cabinets
                .add(ModBlocks.DESK_CABINET_OAK.get().asItem())
                .add(ModBlocks.DESK_CABINET_SPRUCE.get().asItem())
                .add(ModBlocks.DESK_CABINET_BIRCH.get().asItem())
                .add(ModBlocks.DESK_CABINET_JUNGLE.get().asItem())
                .add(ModBlocks.DESK_CABINET_ACACIA.get().asItem())
                .add(ModBlocks.DESK_CABINET_DARK_OAK.get().asItem())
                .add(ModBlocks.DESK_CABINET_STONE.get().asItem())
                .add(ModBlocks.DESK_CABINET_GRANITE.get().asItem())
                .add(ModBlocks.DESK_CABINET_DIORITE.get().asItem())
                .add(ModBlocks.DESK_CABINET_ANDESITE.get().asItem())
                .add(ModBlocks.DESK_CABINET_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.DESK_CABINET_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.DESK_CABINET_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.DESK_CABINET_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.DESK_CABINET_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.DESK_CABINET_STRIPPED_DARK_OAK.get().asItem())
                // Blinds
                .add(ModBlocks.BLINDS_OAK.get().asItem())
                .add(ModBlocks.BLINDS_SPRUCE.get().asItem())
                .add(ModBlocks.BLINDS_BIRCH.get().asItem())
                .add(ModBlocks.BLINDS_JUNGLE.get().asItem())
                .add(ModBlocks.BLINDS_ACACIA.get().asItem())
                .add(ModBlocks.BLINDS_DARK_OAK.get().asItem())
                .add(ModBlocks.BLINDS_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.BLINDS_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.BLINDS_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.BLINDS_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.BLINDS_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.BLINDS_STRIPPED_DARK_OAK.get().asItem());

        this.tag(ModTags.Items.GENERAL)
                // Tables
                .add(ModBlocks.TABLE_OAK.get().asItem())
                .add(ModBlocks.TABLE_SPRUCE.get().asItem())
                .add(ModBlocks.TABLE_BIRCH.get().asItem())
                .add(ModBlocks.TABLE_JUNGLE.get().asItem())
                .add(ModBlocks.TABLE_ACACIA.get().asItem())
                .add(ModBlocks.TABLE_DARK_OAK.get().asItem())
                .add(ModBlocks.TABLE_STONE.get().asItem())
                .add(ModBlocks.TABLE_GRANITE.get().asItem())
                .add(ModBlocks.TABLE_DIORITE.get().asItem())
                .add(ModBlocks.TABLE_ANDESITE.get().asItem())
                .add(ModBlocks.TABLE_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.TABLE_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.TABLE_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.TABLE_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.TABLE_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.TABLE_STRIPPED_DARK_OAK.get().asItem())
                // Chairs
                .add(ModBlocks.CHAIR_OAK.get().asItem())
                .add(ModBlocks.CHAIR_SPRUCE.get().asItem())
                .add(ModBlocks.CHAIR_BIRCH.get().asItem())
                .add(ModBlocks.CHAIR_JUNGLE.get().asItem())
                .add(ModBlocks.CHAIR_ACACIA.get().asItem())
                .add(ModBlocks.CHAIR_DARK_OAK.get().asItem())
                .add(ModBlocks.CHAIR_STONE.get().asItem())
                .add(ModBlocks.CHAIR_GRANITE.get().asItem())
                .add(ModBlocks.CHAIR_DIORITE.get().asItem())
                .add(ModBlocks.CHAIR_ANDESITE.get().asItem())
                .add(ModBlocks.CHAIR_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.CHAIR_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.CHAIR_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.CHAIR_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.CHAIR_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.CHAIR_STRIPPED_DARK_OAK.get().asItem())
                // Coffee Table
                .add(ModBlocks.COFFEE_TABLE_OAK.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_SPRUCE.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_BIRCH.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_JUNGLE.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_ACACIA.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_DARK_OAK.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_STONE.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_GRANITE.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_DIORITE.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_ANDESITE.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.COFFEE_TABLE_STRIPPED_DARK_OAK.get().asItem())
                // Sofa
                .add(ModBlocks.SOFA_WHITE.get().asItem())
                .add(ModBlocks.SOFA_ORANGE.get().asItem())
                .add(ModBlocks.SOFA_MAGENTA.get().asItem())
                .add(ModBlocks.SOFA_LIGHT_BLUE.get().asItem())
                .add(ModBlocks.SOFA_YELLOW.get().asItem())
                .add(ModBlocks.SOFA_LIME.get().asItem())
                .add(ModBlocks.SOFA_PINK.get().asItem())
                .add(ModBlocks.SOFA_GRAY.get().asItem())
                .add(ModBlocks.SOFA_LIGHT_GRAY.get().asItem())
                .add(ModBlocks.SOFA_CYAN.get().asItem())
                .add(ModBlocks.SOFA_PURPLE.get().asItem())
                .add(ModBlocks.SOFA_BLUE.get().asItem())
                .add(ModBlocks.SOFA_BROWN.get().asItem())
                .add(ModBlocks.SOFA_GREEN.get().asItem())
                .add(ModBlocks.SOFA_RED.get().asItem())
                .add(ModBlocks.SOFA_BLACK.get().asItem());

        this.tag(ModTags.Items.KITCHEN)
                // Kitchen Counters
                .add(ModBlocks.KITCHEN_COUNTER_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_SPRUCE.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_BIRCH.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_JUNGLE.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_ACACIA.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_DARK_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_STRIPPED_DARK_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_WHITE.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_ORANGE.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_MAGENTA.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_LIGHT_BLUE.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_YELLOW.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_LIME.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_PINK.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_GRAY.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_LIGHT_GRAY.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_CYAN.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_PURPLE.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_BLUE.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_BROWN.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_GREEN.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_RED.get().asItem())
                .add(ModBlocks.KITCHEN_COUNTER_BLACK.get().asItem())
                // Kitchen Drawers
                .add(ModBlocks.KITCHEN_DRAWER_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_SPRUCE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_BIRCH.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_JUNGLE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_ACACIA.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_DARK_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_STRIPPED_DARK_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_WHITE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_ORANGE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_MAGENTA.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_LIGHT_BLUE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_YELLOW.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_LIME.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_PINK.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_GRAY.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_LIGHT_GRAY.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_CYAN.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_PURPLE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_BLUE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_BROWN.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_GREEN.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_RED.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_BLACK.get().asItem())
                // Spatula
                .add(ModItems.SPATULA.get())
                // Kitchen Sinks
                .add(ModBlocks.KITCHEN_SINK_LIGHT_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_SPRUCE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_BIRCH.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_JUNGLE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_ACACIA.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_DARK_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_STRIPPED_DARK_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_DARK_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_DARK_SPRUCE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_DARK_BIRCH.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_DARK_JUNGLE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_DARK_ACACIA.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_DARK_DARK_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_DARK_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_DARK_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_DARK_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_DARK_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_DARK_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_DARK_STRIPPED_DARK_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_WHITE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_ORANGE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_MAGENTA.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_BLUE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_YELLOW.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIME.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_PINK.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_GRAY.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_LIGHT_GRAY.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_CYAN.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_PURPLE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_BLUE.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_BROWN.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_GREEN.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_RED.get().asItem())
                .add(ModBlocks.KITCHEN_SINK_BLACK.get().asItem())
                //Fridge
                .add(ModBlocks.FRIDGE_LIGHT.get().asItem())
                .add(ModBlocks.FRIDGE_DARK.get().asItem());

        this.tag(ModTags.Items.OUTDOORS)
                // Fences and Fence Gates
                .addTag(ModTags.Items.UPGRADED_FENCE_GATES)
                .addTag(ModTags.Items.UPGRADED_FENCES)
                // Park Benches
                .add(ModBlocks.PARK_BENCH_OAK.get().asItem())
                .add(ModBlocks.PARK_BENCH_SPRUCE.get().asItem())
                .add(ModBlocks.PARK_BENCH_BIRCH.get().asItem())
                .add(ModBlocks.PARK_BENCH_JUNGLE.get().asItem())
                .add(ModBlocks.PARK_BENCH_ACACIA.get().asItem())
                .add(ModBlocks.PARK_BENCH_DARK_OAK.get().asItem())
                .add(ModBlocks.PARK_BENCH_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.PARK_BENCH_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.PARK_BENCH_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.PARK_BENCH_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.PARK_BENCH_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.PARK_BENCH_STRIPPED_DARK_OAK.get().asItem())
                // Post Box
                .add(ModBlocks.POST_BOX.get().asItem())
                // Mail Boxes
                .add(ModBlocks.MAIL_BOX_OAK.get().asItem())
                .add(ModBlocks.MAIL_BOX_SPRUCE.get().asItem())
                .add(ModBlocks.MAIL_BOX_BIRCH.get().asItem())
                .add(ModBlocks.MAIL_BOX_JUNGLE.get().asItem())
                .add(ModBlocks.MAIL_BOX_ACACIA.get().asItem())
                .add(ModBlocks.MAIL_BOX_DARK_OAK.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_DARK_OAK.get().asItem())
                // Hedge
                .addTag(ModTags.Items.HEDGES)
                // Rock Path
                .add(ModBlocks.ROCK_PATH.get().asItem())
                // Trampolines
                .add(ModBlocks.TRAMPOLINE.get().asItem())
                // Coolers
                .add(ModBlocks.COOLER_WHITE.get().asItem())
                .add(ModBlocks.COOLER_ORANGE.get().asItem())
                .add(ModBlocks.COOLER_MAGENTA.get().asItem())
                .add(ModBlocks.COOLER_LIGHT_BLUE.get().asItem())
                .add(ModBlocks.COOLER_YELLOW.get().asItem())
                .add(ModBlocks.COOLER_LIME.get().asItem())
                .add(ModBlocks.COOLER_PINK.get().asItem())
                .add(ModBlocks.COOLER_GRAY.get().asItem())
                .add(ModBlocks.COOLER_LIGHT_GRAY.get().asItem())
                .add(ModBlocks.COOLER_CYAN.get().asItem())
                .add(ModBlocks.COOLER_PURPLE.get().asItem())
                .add(ModBlocks.COOLER_BLUE.get().asItem())
                .add(ModBlocks.COOLER_BROWN.get().asItem())
                .add(ModBlocks.COOLER_GREEN.get().asItem())
                .add(ModBlocks.COOLER_RED.get().asItem())
                .add(ModBlocks.COOLER_BLACK.get().asItem())
                // Grill
                .add(ModBlocks.GRILL_WHITE.get().asItem())
                .add(ModBlocks.GRILL_ORANGE.get().asItem())
                .add(ModBlocks.GRILL_MAGENTA.get().asItem())
                .add(ModBlocks.GRILL_LIGHT_BLUE.get().asItem())
                .add(ModBlocks.GRILL_YELLOW.get().asItem())
                .add(ModBlocks.GRILL_LIME.get().asItem())
                .add(ModBlocks.GRILL_PINK.get().asItem())
                .add(ModBlocks.GRILL_GRAY.get().asItem())
                .add(ModBlocks.GRILL_LIGHT_GRAY.get().asItem())
                .add(ModBlocks.GRILL_CYAN.get().asItem())
                .add(ModBlocks.GRILL_PURPLE.get().asItem())
                .add(ModBlocks.GRILL_BLUE.get().asItem())
                .add(ModBlocks.GRILL_BROWN.get().asItem())
                .add(ModBlocks.GRILL_GREEN.get().asItem())
                .add(ModBlocks.GRILL_RED.get().asItem())
                .add(ModBlocks.GRILL_BLACK.get().asItem())
                // Spatula
                .add(ModItems.SPATULA.get());

        this.tag(ModTags.Items.STORAGE)
                // Cabinets
                .add(ModBlocks.CABINET_OAK.get().asItem())
                .add(ModBlocks.CABINET_SPRUCE.get().asItem())
                .add(ModBlocks.CABINET_BIRCH.get().asItem())
                .add(ModBlocks.CABINET_JUNGLE.get().asItem())
                .add(ModBlocks.CABINET_ACACIA.get().asItem())
                .add(ModBlocks.CABINET_DARK_OAK.get().asItem())
                .add(ModBlocks.CABINET_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.CABINET_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.CABINET_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.CABINET_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.CABINET_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.CABINET_STRIPPED_DARK_OAK.get().asItem())
                // Bedside Cabinets
                .add(ModBlocks.BEDSIDE_CABINET_OAK.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_SPRUCE.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_BIRCH.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_JUNGLE.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_ACACIA.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_DARK_OAK.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.BEDSIDE_CABINET_STRIPPED_DARK_OAK.get().asItem())
                // Desk Cabinets
                .add(ModBlocks.DESK_CABINET_OAK.get().asItem())
                .add(ModBlocks.DESK_CABINET_SPRUCE.get().asItem())
                .add(ModBlocks.DESK_CABINET_BIRCH.get().asItem())
                .add(ModBlocks.DESK_CABINET_JUNGLE.get().asItem())
                .add(ModBlocks.DESK_CABINET_ACACIA.get().asItem())
                .add(ModBlocks.DESK_CABINET_DARK_OAK.get().asItem())
                .add(ModBlocks.DESK_CABINET_STONE.get().asItem())
                .add(ModBlocks.DESK_CABINET_GRANITE.get().asItem())
                .add(ModBlocks.DESK_CABINET_DIORITE.get().asItem())
                .add(ModBlocks.DESK_CABINET_ANDESITE.get().asItem())
                .add(ModBlocks.DESK_CABINET_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.DESK_CABINET_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.DESK_CABINET_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.DESK_CABINET_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.DESK_CABINET_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.DESK_CABINET_STRIPPED_DARK_OAK.get().asItem())
                // Crate
                .add(ModBlocks.CRATE_OAK.get().asItem())
                .add(ModBlocks.CRATE_SPRUCE.get().asItem())
                .add(ModBlocks.CRATE_BIRCH.get().asItem())
                .add(ModBlocks.CRATE_JUNGLE.get().asItem())
                .add(ModBlocks.CRATE_ACACIA.get().asItem())
                .add(ModBlocks.CRATE_DARK_OAK.get().asItem())
                .add(ModBlocks.CRATE_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.CRATE_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.CRATE_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.CRATE_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.CRATE_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.CRATE_STRIPPED_DARK_OAK.get().asItem())
                // Mailbox
                .add(ModBlocks.MAIL_BOX_OAK.get().asItem())
                .add(ModBlocks.MAIL_BOX_SPRUCE.get().asItem())
                .add(ModBlocks.MAIL_BOX_BIRCH.get().asItem())
                .add(ModBlocks.MAIL_BOX_JUNGLE.get().asItem())
                .add(ModBlocks.MAIL_BOX_ACACIA.get().asItem())
                .add(ModBlocks.MAIL_BOX_DARK_OAK.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_DARK_OAK.get().asItem())
                // Coolers
                .add(ModBlocks.COOLER_WHITE.get().asItem())
                .add(ModBlocks.COOLER_ORANGE.get().asItem())
                .add(ModBlocks.COOLER_MAGENTA.get().asItem())
                .add(ModBlocks.COOLER_LIGHT_BLUE.get().asItem())
                .add(ModBlocks.COOLER_YELLOW.get().asItem())
                .add(ModBlocks.COOLER_LIME.get().asItem())
                .add(ModBlocks.COOLER_PINK.get().asItem())
                .add(ModBlocks.COOLER_GRAY.get().asItem())
                .add(ModBlocks.COOLER_LIGHT_GRAY.get().asItem())
                .add(ModBlocks.COOLER_CYAN.get().asItem())
                .add(ModBlocks.COOLER_PURPLE.get().asItem())
                .add(ModBlocks.COOLER_BLUE.get().asItem())
                .add(ModBlocks.COOLER_BROWN.get().asItem())
                .add(ModBlocks.COOLER_GREEN.get().asItem())
                .add(ModBlocks.COOLER_RED.get().asItem())
                .add(ModBlocks.COOLER_BLACK.get().asItem())
                // Park Benches
                .add(ModBlocks.PARK_BENCH_OAK.get().asItem())
                .add(ModBlocks.PARK_BENCH_SPRUCE.get().asItem())
                .add(ModBlocks.PARK_BENCH_BIRCH.get().asItem())
                .add(ModBlocks.PARK_BENCH_JUNGLE.get().asItem())
                .add(ModBlocks.PARK_BENCH_ACACIA.get().asItem())
                .add(ModBlocks.PARK_BENCH_DARK_OAK.get().asItem())
                .add(ModBlocks.PARK_BENCH_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.PARK_BENCH_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.PARK_BENCH_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.PARK_BENCH_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.PARK_BENCH_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.PARK_BENCH_STRIPPED_DARK_OAK.get().asItem())
                // Post Box
                .add(ModBlocks.POST_BOX.get().asItem())
                // Mail Boxes
                .add(ModBlocks.MAIL_BOX_OAK.get().asItem())
                .add(ModBlocks.MAIL_BOX_SPRUCE.get().asItem())
                .add(ModBlocks.MAIL_BOX_BIRCH.get().asItem())
                .add(ModBlocks.MAIL_BOX_JUNGLE.get().asItem())
                .add(ModBlocks.MAIL_BOX_ACACIA.get().asItem())
                .add(ModBlocks.MAIL_BOX_DARK_OAK.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.MAIL_BOX_STRIPPED_DARK_OAK.get().asItem())
                // Coolers
                .add(ModBlocks.COOLER_WHITE.get().asItem())
                .add(ModBlocks.COOLER_ORANGE.get().asItem())
                .add(ModBlocks.COOLER_MAGENTA.get().asItem())
                .add(ModBlocks.COOLER_LIGHT_BLUE.get().asItem())
                .add(ModBlocks.COOLER_YELLOW.get().asItem())
                .add(ModBlocks.COOLER_LIME.get().asItem())
                .add(ModBlocks.COOLER_PINK.get().asItem())
                .add(ModBlocks.COOLER_GRAY.get().asItem())
                .add(ModBlocks.COOLER_LIGHT_GRAY.get().asItem())
                .add(ModBlocks.COOLER_CYAN.get().asItem())
                .add(ModBlocks.COOLER_PURPLE.get().asItem())
                .add(ModBlocks.COOLER_BLUE.get().asItem())
                .add(ModBlocks.COOLER_BROWN.get().asItem())
                .add(ModBlocks.COOLER_GREEN.get().asItem())
                .add(ModBlocks.COOLER_RED.get().asItem())
                .add(ModBlocks.COOLER_BLACK.get().asItem())
                // Kitchen Drawers
                .add(ModBlocks.KITCHEN_DRAWER_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_SPRUCE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_BIRCH.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_JUNGLE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_ACACIA.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_DARK_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_STRIPPED_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_STRIPPED_SPRUCE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_STRIPPED_BIRCH.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_STRIPPED_JUNGLE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_STRIPPED_ACACIA.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_STRIPPED_DARK_OAK.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_WHITE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_ORANGE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_MAGENTA.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_LIGHT_BLUE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_YELLOW.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_LIME.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_PINK.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_GRAY.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_LIGHT_GRAY.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_CYAN.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_PURPLE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_BLUE.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_BROWN.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_GREEN.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_RED.get().asItem())
                .add(ModBlocks.KITCHEN_DRAWER_BLACK.get().asItem());

        this.tag(ModTags.Items.TRAMPOLINE)
                // Trampolines
                .add(ModBlocks.TRAMPOLINE.get().asItem());

        this.tag(ModTags.Items.ITEMS).add(ModItems.SPATULA.get());

        this.copy(ModTags.Blocks.UPGRADED_FENCE_GATES, ModTags.Items.UPGRADED_FENCE_GATES);
        this.copy(ModTags.Blocks.PICKET_FENCE_GATES, ModTags.Items.PICKET_FENCE_GATES);
        this.copy(ModTags.Blocks.UPGRADED_FENCES, ModTags.Items.UPGRADED_FENCES);
        this.copy(ModTags.Blocks.PICKET_FENCES, ModTags.Items.PICKET_FENCES);
        this.copy(ModTags.Blocks.HEDGES, ModTags.Items.HEDGES);
    }
}
