@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mrcrayfish.furniture.datagen;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;