package com.mrcrayfish.furniture.core;

import com.mrcrayfish.furniture.FurnitureMod;
import com.mrcrayfish.furniture.Reference;
import com.mrcrayfish.furniture.block.*;
import com.mrcrayfish.furniture.item.BlockSupplierItem;
import com.mrcrayfish.furniture.item.DoorMatItem;
import com.mrcrayfish.furniture.item.TrampolineItem;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.block.material.PushReaction;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

import javax.annotation.Nullable;
import java.util.function.Function;
import java.util.function.Supplier;

/**
 * Author: MrCrayfish
 */
public class ModBlocks
{
    public static final DeferredRegister<Block> REGISTER = DeferredRegister.create(ForgeRegistries.BLOCKS, Reference.MOD_ID);

    public static final Material WOOD = new Material(MaterialColor.WOOD, false, false, false, false, true, false, PushReaction.NORMAL);
    public static final Material STONE = new Material(MaterialColor.STONE, false, false, false, false, true, false, PushReaction.NORMAL);
    public static final Material WOOL = new Material(MaterialColor.WOOL, false, false, false, false, true, false, PushReaction.NORMAL);

    public static final RegistryObject<Block> TABLE_OAK = register("oak_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_SPRUCE = register("spruce_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_BIRCH = register("birch_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_JUNGLE = register("jungle_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_ACACIA = register("acacia_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_DARK_OAK = register("dark_oak_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_CRIMSON = register("crimson_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_WARPED = register("warped_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_STONE = register("stone_table", new TableBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> TABLE_GRANITE = register("granite_table", new TableBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> TABLE_DIORITE = register("diorite_table", new TableBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> TABLE_ANDESITE = register("andesite_table", new TableBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> TABLE_STRIPPED_OAK = register("stripped_oak_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_STRIPPED_SPRUCE = register("stripped_spruce_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_STRIPPED_BIRCH = register("stripped_birch_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_STRIPPED_JUNGLE = register("stripped_jungle_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_STRIPPED_ACACIA = register("stripped_acacia_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_STRIPPED_DARK_OAK = register("stripped_dark_oak_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_STRIPPED_CRIMSON = register("stripped_crimson_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> TABLE_STRIPPED_WARPED = register("stripped_warped_table", new TableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_OAK = register("oak_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_SPRUCE = register("spruce_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_BIRCH = register("birch_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_JUNGLE = register("jungle_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_ACACIA = register("acacia_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_DARK_OAK = register("dark_oak_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_CRIMSON = register("crimson_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_WARPED = register("warped_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_STONE = register("stone_chair", new ChairBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CHAIR_GRANITE = register("granite_chair", new ChairBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CHAIR_DIORITE = register("diorite_chair", new ChairBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CHAIR_ANDESITE = register("andesite_chair", new ChairBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CHAIR_STRIPPED_OAK = register("stripped_oak_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_STRIPPED_SPRUCE = register("stripped_spruce_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_STRIPPED_BIRCH = register("stripped_birch_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_STRIPPED_JUNGLE = register("stripped_jungle_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_STRIPPED_ACACIA = register("stripped_acacia_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_STRIPPED_DARK_OAK = register("stripped_dark_oak_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_STRIPPED_CRIMSON = register("stripped_crimson_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CHAIR_STRIPPED_WARPED = register("stripped_warped_chair", new ChairBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_OAK = register("oak_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_SPRUCE = register("spruce_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_BIRCH = register("birch_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_JUNGLE = register("jungle_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_ACACIA = register("acacia_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_DARK_OAK = register("dark_oak_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_CRIMSON = register("crimson_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_WARPED = register("warped_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_STONE = register("stone_coffee_table", new CoffeeTableBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> COFFEE_TABLE_GRANITE = register("granite_coffee_table", new CoffeeTableBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> COFFEE_TABLE_DIORITE = register("diorite_coffee_table", new CoffeeTableBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> COFFEE_TABLE_ANDESITE = register("andesite_coffee_table", new CoffeeTableBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> COFFEE_TABLE_STRIPPED_OAK = register("stripped_oak_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_STRIPPED_SPRUCE = register("stripped_spruce_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_STRIPPED_BIRCH = register("stripped_birch_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_STRIPPED_JUNGLE = register("stripped_jungle_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_STRIPPED_ACACIA = register("stripped_acacia_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_STRIPPED_DARK_OAK = register("stripped_dark_oak_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_STRIPPED_CRIMSON = register("stripped_crimson_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> COFFEE_TABLE_STRIPPED_WARPED = register("stripped_warped_coffee_table", new CoffeeTableBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_OAK = register("oak_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_SPRUCE = register("spruce_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_BIRCH = register("birch_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_JUNGLE = register("jungle_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_ACACIA = register("acacia_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_DARK_OAK = register("dark_oak_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_CRIMSON = register("crimson_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_WARPED = register("warped_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_STONE = register("stone_cabinet", new CabinetBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CABINET_GRANITE = register("granite_cabinet", new CabinetBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CABINET_DIORITE = register("diorite_cabinet", new CabinetBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CABINET_ANDESITE = register("andesite_cabinet", new CabinetBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> CABINET_STRIPPED_OAK = register("stripped_oak_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_STRIPPED_SPRUCE = register("stripped_spruce_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_STRIPPED_BIRCH = register("stripped_birch_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_STRIPPED_JUNGLE = register("stripped_jungle_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_STRIPPED_ACACIA = register("stripped_acacia_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_STRIPPED_DARK_OAK = register("stripped_dark_oak_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_STRIPPED_CRIMSON = register("stripped_crimson_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CABINET_STRIPPED_WARPED = register("stripped_warped_cabinet", new CabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_OAK = register("oak_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_SPRUCE = register("spruce_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_BIRCH = register("birch_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_JUNGLE = register("jungle_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_ACACIA = register("acacia_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_DARK_OAK = register("dark_oak_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_CRIMSON = register("crimson_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_WARPED = register("warped_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_STONE = register("stone_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_GRANITE = register("granite_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_DIORITE = register("diorite_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_ANDESITE = register("andesite_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_STRIPPED_OAK = register("stripped_oak_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_STRIPPED_SPRUCE = register("stripped_spruce_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_STRIPPED_BIRCH = register("stripped_birch_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_STRIPPED_JUNGLE = register("stripped_jungle_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_STRIPPED_ACACIA = register("stripped_acacia_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_STRIPPED_DARK_OAK = register("stripped_dark_oak_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_STRIPPED_CRIMSON = register("stripped_crimson_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BEDSIDE_CABINET_STRIPPED_WARPED = register("stripped_warped_bedside_cabinet", new BedsideCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> DESK_OAK = register("oak_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.OAK));
    public static final RegistryObject<Block> DESK_SPRUCE = register("spruce_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.BIRCH));
    public static final RegistryObject<Block> DESK_BIRCH = register("birch_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.SPRUCE));
    public static final RegistryObject<Block> DESK_JUNGLE = register("jungle_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.JUNGLE));
    public static final RegistryObject<Block> DESK_ACACIA = register("acacia_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.ACACIA));
    public static final RegistryObject<Block> DESK_DARK_OAK = register("dark_oak_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.DARK_OAK));
    public static final RegistryObject<Block> DESK_CRIMSON = register("crimson_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.DARK_OAK));
    public static final RegistryObject<Block> DESK_WARPED = register("warped_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.DARK_OAK));
    public static final RegistryObject<Block> DESK_STONE = register("stone_desk", new DeskBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE), DeskBlock.MaterialType.STONE));
    public static final RegistryObject<Block> DESK_GRANITE = register("granite_desk", new DeskBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE), DeskBlock.MaterialType.GRANITE));
    public static final RegistryObject<Block> DESK_DIORITE = register("diorite_desk", new DeskBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE), DeskBlock.MaterialType.DIORITE));
    public static final RegistryObject<Block> DESK_ANDESITE = register("andesite_desk", new DeskBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE), DeskBlock.MaterialType.ANDESITE));
    public static final RegistryObject<Block> DESK_STRIPPED_OAK = register("stripped_oak_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.STRIPPED_OAK));
    public static final RegistryObject<Block> DESK_STRIPPED_SPRUCE = register("stripped_spruce_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.STRIPPED_BIRCH));
    public static final RegistryObject<Block> DESK_STRIPPED_BIRCH = register("stripped_birch_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.STRIPPED_SPRUCE));
    public static final RegistryObject<Block> DESK_STRIPPED_JUNGLE = register("stripped_jungle_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.STRIPPED_JUNGLE));
    public static final RegistryObject<Block> DESK_STRIPPED_ACACIA = register("stripped_acacia_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.STRIPPED_ACACIA));
    public static final RegistryObject<Block> DESK_STRIPPED_DARK_OAK = register("stripped_dark_oak_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.STRIPPED_DARK_OAK));
    public static final RegistryObject<Block> DESK_STRIPPED_CRIMSON = register("stripped_crimson_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.DARK_OAK));
    public static final RegistryObject<Block> DESK_STRIPPED_WARPED = register("stripped_warped_desk", new DeskBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.DARK_OAK));
    public static final RegistryObject<Block> DESK_CABINET_OAK = register("oak_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.OAK));
    public static final RegistryObject<Block> DESK_CABINET_SPRUCE = register("spruce_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.BIRCH));
    public static final RegistryObject<Block> DESK_CABINET_BIRCH = register("birch_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.SPRUCE));
    public static final RegistryObject<Block> DESK_CABINET_JUNGLE = register("jungle_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.JUNGLE));
    public static final RegistryObject<Block> DESK_CABINET_ACACIA = register("acacia_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.ACACIA));
    public static final RegistryObject<Block> DESK_CABINET_CRIMSON = register("crimson_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.DARK_OAK));
    public static final RegistryObject<Block> DESK_CABINET_WARPED = register("warped_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.DARK_OAK));
    public static final RegistryObject<Block> DESK_CABINET_DARK_OAK = register("dark_oak_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.DARK_OAK));
    public static final RegistryObject<Block> DESK_CABINET_STONE = register("stone_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE), DeskBlock.MaterialType.STONE));
    public static final RegistryObject<Block> DESK_CABINET_GRANITE = register("granite_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE), DeskBlock.MaterialType.GRANITE));
    public static final RegistryObject<Block> DESK_CABINET_DIORITE = register("diorite_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE), DeskBlock.MaterialType.DIORITE));
    public static final RegistryObject<Block> DESK_CABINET_ANDESITE = register("andesite_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(STONE).hardnessAndResistance(1.0F).sound(SoundType.STONE), DeskBlock.MaterialType.ANDESITE));
    public static final RegistryObject<Block> DESK_CABINET_STRIPPED_OAK = register("stripped_oak_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.STRIPPED_OAK));
    public static final RegistryObject<Block> DESK_CABINET_STRIPPED_SPRUCE = register("stripped_spruce_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.STRIPPED_BIRCH));
    public static final RegistryObject<Block> DESK_CABINET_STRIPPED_BIRCH = register("stripped_birch_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.STRIPPED_SPRUCE));
    public static final RegistryObject<Block> DESK_CABINET_STRIPPED_JUNGLE = register("stripped_jungle_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.STRIPPED_JUNGLE));
    public static final RegistryObject<Block> DESK_CABINET_STRIPPED_ACACIA = register("stripped_acacia_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.STRIPPED_ACACIA));
    public static final RegistryObject<Block> DESK_CABINET_STRIPPED_DARK_OAK = register("stripped_dark_oak_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.STRIPPED_DARK_OAK));
    public static final RegistryObject<Block> DESK_CABINET_STRIPPED_CRIMSON = register("stripped_crimson_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.DARK_OAK));
    public static final RegistryObject<Block> DESK_CABINET_STRIPPED_WARPED = register("stripped_warped_desk_cabinet", new DeskCabinetBlock(Block.Properties.create(WOOD).hardnessAndResistance(1.0F).sound(SoundType.WOOD), DeskBlock.MaterialType.DARK_OAK));
    public static final RegistryObject<Block> SOFA_WHITE = register("white_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.SNOW).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_ORANGE = register("orange_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.ADOBE).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_MAGENTA = register("magenta_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.MAGENTA).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_LIGHT_BLUE = register("light_blue_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.LIGHT_BLUE).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_YELLOW = register("yellow_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_LIME = register("lime_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.LIME).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_PINK = register("pink_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.PINK).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_GRAY = register("gray_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.GRAY).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_LIGHT_GRAY = register("light_gray_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.LIGHT_GRAY).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_CYAN = register("cyan_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.CYAN).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_PURPLE = register("purple_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.PURPLE).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_BLUE = register("blue_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.BLUE).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_BROWN = register("brown_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.BROWN).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_GREEN = register("green_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.GREEN).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_RED = register("red_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.RED).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_BLACK = register("black_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.BLACK).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> SOFA_RAINBOW = register("rainbow_sofa", new SofaBlock(Block.Properties.create(WOOL, MaterialColor.SNOW).hardnessAndResistance(0.5F).sound(SoundType.WOOD)), new Item.Properties());
    public static final RegistryObject<Block> BLINDS_OAK = register("oak_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_SPRUCE = register("spruce_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_BIRCH = register("birch_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_JUNGLE = register("jungle_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_ACACIA = register("acacia_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_DARK_OAK = register("dark_oak_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_CRIMSON = register("crimson_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_WARPED = register("warped_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_STRIPPED_OAK = register("stripped_oak_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_STRIPPED_SPRUCE = register("stripped_spruce_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_STRIPPED_BIRCH = register("stripped_birch_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_STRIPPED_JUNGLE = register("stripped_jungle_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_STRIPPED_ACACIA = register("stripped_acacia_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_STRIPPED_DARK_OAK = register("stripped_dark_oak_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_STRIPPED_CRIMSON = register("stripped_crimson_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> BLINDS_STRIPPED_WARPED = register("stripped_warped_blinds", new BlindsBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_OAK = register("oak_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_SPRUCE = register("spruce_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_BIRCH = register("birch_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_JUNGLE = register("jungle_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_ACACIA = register("acacia_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_DARK_OAK = register("dark_oak_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_CRIMSON = register("crimson_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_WARPED = register("warped_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_STRIPPED_OAK = register("stripped_oak_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_STRIPPED_SPRUCE = register("stripped_spruce_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_STRIPPED_BIRCH = register("stripped_birch_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_STRIPPED_JUNGLE = register("stripped_jungle_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_STRIPPED_ACACIA = register("stripped_acacia_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_STRIPPED_DARK_OAK = register("stripped_dark_oak_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_STRIPPED_CRIMSON = register("stripped_crimson_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_FENCE_STRIPPED_WARPED = register("stripped_warped_upgraded_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_OAK = register("oak_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_SPRUCE = register("spruce_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_BIRCH = register("birch_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_JUNGLE = register("jungle_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_ACACIA = register("acacia_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_DARK_OAK = register("dark_oak_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_CRIMSON = register("crimson_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_WARPED = register("warped_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_STRIPPED_OAK = register("stripped_oak_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_STRIPPED_SPRUCE = register("stripped_spruce_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_STRIPPED_BIRCH = register("stripped_birch_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_STRIPPED_JUNGLE = register("stripped_jungle_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_STRIPPED_ACACIA = register("stripped_acacia_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_STRIPPED_DARK_OAK = register("stripped_dark_oak_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_STRIPPED_CRIMSON = register("stripped_crimson_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> UPGRADED_GATE_STRIPPED_WARPED = register("stripped_warped_upgraded_gate", new UpgradedGateBlock(Block.Properties.create(WOOD).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_WHITE = register("white_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.SNOW).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_ORANGE = register("orange_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.ADOBE).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_MAGENTA = register("magenta_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.MAGENTA).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_LIGHT_BLUE = register("light_blue_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.LIGHT_BLUE).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_YELLOW = register("yellow_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_LIME = register("lime_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.LIME).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_PINK = register("pink_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.PINK).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_GRAY = register("gray_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.GRAY).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_LIGHT_GRAY = register("light_gray_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.LIGHT_GRAY).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_CYAN = register("cyan_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.CYAN).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_PURPLE = register("purple_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.PURPLE).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_BLUE = register("blue_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.BLUE).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_BROWN = register("brown_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.BROWN).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_GREEN = register("green_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.GREEN).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_RED = register("red_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.RED).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_FENCE_BLACK = register("black_picket_fence", new UpgradedFenceBlock(Block.Properties.create(WOOD, MaterialColor.BLACK).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_WHITE = register("white_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.SNOW).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_ORANGE = register("orange_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.ADOBE).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_MAGENTA = register("magenta_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.MAGENTA).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_LIGHT_BLUE = register("light_blue_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.LIGHT_BLUE).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_YELLOW = register("yellow_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_LIME = register("lime_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.LIME).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_PINK = register("pink_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.PINK).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_GRAY = register("gray_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.GRAY).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_LIGHT_GRAY = register("light_gray_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.LIGHT_GRAY).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_CYAN = register("cyan_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.CYAN).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_PURPLE = register("purple_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.PURPLE).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_BLUE = register("blue_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.BLUE).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_BROWN = register("brown_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.BROWN).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_GREEN = register("green_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.GREEN).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_RED = register("red_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.RED).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PICKET_GATE_BLACK = register("black_picket_gate", new UpgradedGateBlock(Block.Properties.create(WOOD, MaterialColor.BLACK).hardnessAndResistance(0.5F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_OAK = register("oak_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_SPRUCE = register("spruce_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_BIRCH = register("birch_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_JUNGLE = register("jungle_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_ACACIA = register("acacia_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_DARK_OAK = register("dark_oak_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_CRIMSON = register("crimson_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_WARPED = register("warped_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_STRIPPED_OAK = register("stripped_oak_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_STRIPPED_SPRUCE = register("stripped_spruce_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_STRIPPED_BIRCH = register("stripped_birch_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_STRIPPED_JUNGLE = register("stripped_jungle_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_STRIPPED_ACACIA = register("stripped_acacia_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_STRIPPED_DARK_OAK = register("stripped_dark_oak_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_STRIPPED_CRIMSON = register("stripped_crimson_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> CRATE_STRIPPED_WARPED = register("stripped_warped_crate", new CrateBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_OAK = register("oak_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_SPRUCE = register("spruce_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_BIRCH = register("birch_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_JUNGLE = register("jungle_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_ACACIA = register("acacia_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_DARK_OAK = register("dark_oak_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_CRIMSON = register("crimson_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_WARPED = register("warped_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_STRIPPED_OAK = register("stripped_oak_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_STRIPPED_SPRUCE = register("stripped_spruce_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_STRIPPED_BIRCH = register("stripped_birch_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_STRIPPED_JUNGLE = register("stripped_jungle_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_STRIPPED_ACACIA = register("stripped_acacia_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_STRIPPED_DARK_OAK = register("stripped_dark_oak_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_STRIPPED_CRIMSON = register("stripped_crimson_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> PARK_BENCH_STRIPPED_WARPED = register("stripped_warped_park_bench", new ParkBenchBlock(Block.Properties.create(WOOD).hardnessAndResistance(2.0F, 10.0F).sound(SoundType.WOOD)));
    public static final RegistryObject<Block> POST_BOX = register("post_box", new PostBoxBlock(Block.Properties.from(Blocks.ANVIL)));
    public static final RegistryObject<Block> MAIL_BOX_OAK = register("oak_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_SPRUCE = register("spruce_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.SPRUCE_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_BIRCH = register("birch_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.BIRCH_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_JUNGLE = register("jungle_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.JUNGLE_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_ACACIA = register("acacia_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.ACACIA_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_DARK_OAK = register("dark_oak_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.DARK_OAK_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_CRIMSON = register("crimson_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.DARK_OAK_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_WARPED = register("warped_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.DARK_OAK_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_STRIPPED_OAK = register("stripped_oak_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_STRIPPED_SPRUCE = register("stripped_spruce_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.SPRUCE_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_STRIPPED_BIRCH = register("stripped_birch_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.BIRCH_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_STRIPPED_JUNGLE = register("stripped_jungle_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.JUNGLE_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_STRIPPED_ACACIA = register("stripped_acacia_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.ACACIA_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_STRIPPED_DARK_OAK = register("stripped_dark_oak_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.DARK_OAK_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_STRIPPED_CRIMSON = register("stripped_crimson_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.DARK_OAK_PLANKS)));
    public static final RegistryObject<Block> MAIL_BOX_STRIPPED_WARPED = register("stripped_warped_mail_box", new MailBoxBlock(Block.Properties.from(Blocks.DARK_OAK_PLANKS)));
    public static final RegistryObject<Block> HEDGE_OAK = register("oak_hedge", new HedgeBlock(Block.Properties.from(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> HEDGE_SPRUCE = register("spruce_hedge", new HedgeBlock(Block.Properties.from(Blocks.SPRUCE_LEAVES)));
    public static final RegistryObject<Block> HEDGE_BIRCH = register("birch_hedge", new HedgeBlock(Block.Properties.from(Blocks.BIRCH_LEAVES)));
    public static final RegistryObject<Block> HEDGE_JUNGLE = register("jungle_hedge", new HedgeBlock(Block.Properties.from(Blocks.JUNGLE_LEAVES)));
    public static final RegistryObject<Block> HEDGE_ACACIA = register("acacia_hedge", new HedgeBlock(Block.Properties.from(Blocks.ACACIA_LEAVES)));
    public static final RegistryObject<Block> HEDGE_DARK_OAK = register("dark_oak_hedge", new HedgeBlock(Block.Properties.from(Blocks.DARK_OAK_LEAVES)));
    public static final RegistryObject<Block> ROCK_PATH = register("rock_path", new RockPath(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> TRAMPOLINE = register("trampoline", new TrampolineBlock(Block.Properties.from(Blocks.STONE)), block -> new TrampolineItem(block, new Item.Properties().group(FurnitureMod.GROUP)));
    public static final RegistryObject<Block> COOLER_WHITE = register("white_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_ORANGE = register("orange_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_MAGENTA = register("magenta_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_LIGHT_BLUE = register("light_blue_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_YELLOW = register("yellow_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_LIME = register("lime_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_PINK = register("pink_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_GRAY = register("gray_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_LIGHT_GRAY = register("light_gray_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_CYAN = register("cyan_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_PURPLE = register("purple_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_BLUE = register("blue_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_BROWN = register("brown_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_GREEN = register("green_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_RED = register("red_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> COOLER_BLACK = register("black_cooler", new CoolerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> GRILL_WHITE = register("white_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_ORANGE = register("orange_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_MAGENTA = register("magenta_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_LIGHT_BLUE = register("light_blue_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_YELLOW = register("yellow_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_LIME = register("lime_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_PINK = register("pink_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_GRAY = register("gray_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_LIGHT_GRAY = register("light_gray_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_CYAN = register("cyan_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_PURPLE = register("purple_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_BLUE = register("blue_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_BROWN = register("brown_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_GREEN = register("green_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_RED = register("red_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> GRILL_BLACK = register("black_grill", new GrillBlock(Block.Properties.from(Blocks.STONE)));
    public static final RegistryObject<Block> DOOR_MAT = register("door_mat", new DoorMatBlock(Block.Properties.from(Blocks.WHITE_WOOL)), block -> new DoorMatItem(block, new Item.Properties().group(FurnitureMod.GROUP)));
    public static final RegistryObject<Block> DIVING_BOARD = register("diving_board", new DivingBoardBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_OAK = register("oak_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_SPRUCE = register("spruce_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_BIRCH = register("birch_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_JUNGLE = register("jungle_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_ACACIA = register("acacia_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_DARK_OAK = register("dark_oak_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_CRIMSON = register("crimson_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_WARPED = register("warped_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_STRIPPED_OAK = register("stripped_oak_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_STRIPPED_SPRUCE = register("stripped_spruce_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_STRIPPED_BIRCH = register("stripped_birch_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_STRIPPED_JUNGLE = register("stripped_jungle_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_STRIPPED_ACACIA = register("stripped_acacia_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_STRIPPED_DARK_OAK = register("stripped_dark_oak_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_STRIPPED_CRIMSON = register("stripped_crimson_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_STRIPPED_WARPED = register("stripped_warped_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_WHITE = register("white_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_ORANGE = register("orange_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_MAGENTA = register("magenta_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_LIGHT_BLUE = register("light_blue_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_YELLOW = register("yellow_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_LIME = register("lime_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_PINK = register("pink_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_GRAY = register("gray_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_LIGHT_GRAY = register("light_gray_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_CYAN = register("cyan_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_PURPLE = register("purple_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_BLUE = register("blue_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_BROWN = register("brown_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_GREEN = register("green_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_RED = register("red_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_COUNTER_BLACK = register("black_kitchen_counter", new KitchenCounterBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_OAK = register("oak_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_SPRUCE = register("spruce_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_BIRCH = register("birch_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_JUNGLE = register("jungle_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_ACACIA = register("acacia_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_DARK_OAK = register("dark_oak_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_CRIMSON = register("crimson_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_WARPED = register("warped_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_STRIPPED_OAK = register("stripped_oak_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_STRIPPED_SPRUCE = register("stripped_spruce_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_STRIPPED_BIRCH = register("stripped_birch_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_STRIPPED_JUNGLE = register("stripped_jungle_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_STRIPPED_ACACIA = register("stripped_acacia_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_STRIPPED_DARK_OAK = register("stripped_dark_oak_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_STRIPPED_CRIMSON = register("stripped_crimson_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_STRIPPED_WARPED = register("stripped_warped_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_WHITE = register("white_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_ORANGE = register("orange_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_MAGENTA = register("magenta_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_LIGHT_BLUE = register("light_blue_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_YELLOW = register("yellow_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_LIME = register("lime_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_PINK = register("pink_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_GRAY = register("gray_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_LIGHT_GRAY = register("light_gray_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_CYAN = register("cyan_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_PURPLE = register("purple_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_BLUE = register("blue_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_BROWN = register("brown_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_GREEN = register("green_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_RED = register("red_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_DRAWER_BLACK = register("black_kitchen_drawer", new KitchenDrawerBlock(Block.Properties.from(Blocks.OAK_PLANKS)));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_OAK = register("oak_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_SPRUCE = register("spruce_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_BIRCH = register("birch_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_JUNGLE = register("jungle_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_ACACIA = register("acacia_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_DARK_OAK = register("dark_oak_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_CRIMSON = register("crimson_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_WARPED = register("warped_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_STRIPPED_OAK = register("stripped_oak_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_STRIPPED_SPRUCE = register("stripped_spruce_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_STRIPPED_BIRCH = register("stripped_birch_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_STRIPPED_JUNGLE = register("stripped_jungle_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_STRIPPED_ACACIA = register("stripped_acacia_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_STRIPPED_DARK_OAK = register("stripped_dark_oak_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_STRIPPED_CRIMSON = register("stripped_crimson_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_STRIPPED_WARPED = register("stripped_warped_kitchen_sink_light", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_OAK = register("oak_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_SPRUCE = register("spruce_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_BIRCH = register("birch_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_JUNGLE = register("jungle_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_ACACIA = register("acacia_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_DARK_OAK = register("dark_oak_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_CRIMSON = register("crimson_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_WARPED = register("warped_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_STRIPPED_OAK = register("stripped_oak_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_STRIPPED_SPRUCE = register("stripped_spruce_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_STRIPPED_BIRCH = register("stripped_birch_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_STRIPPED_JUNGLE = register("stripped_jungle_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_STRIPPED_ACACIA = register("stripped_acacia_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_STRIPPED_DARK_OAK = register("stripped_dark_oak_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_STRIPPED_CRIMSON = register("stripped_crimson_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_DARK_STRIPPED_WARPED = register("stripped_warped_kitchen_sink_dark", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), true));
    public static final RegistryObject<Block> KITCHEN_SINK_WHITE = register("white_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_ORANGE = register("orange_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_MAGENTA = register("magenta_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_BLUE = register("light_blue_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_YELLOW = register("yellow_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_LIME = register("lime_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_PINK = register("pink_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_GRAY = register("gray_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_LIGHT_GRAY = register("light_gray_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_CYAN = register("cyan_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_PURPLE = register("purple_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_BLUE = register("blue_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_BROWN = register("brown_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_GREEN = register("green_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_RED = register("red_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> KITCHEN_SINK_BLACK = register("black_kitchen_sink", new KitchenSinkBlock(Block.Properties.from(Blocks.OAK_PLANKS), false));
    public static final RegistryObject<Block> FREEZER_LIGHT = register("freezer_light", new FreezerBlock(Block.Properties.from(Blocks.IRON_BLOCK), () -> ModBlocks.FRIDGE_LIGHT), (Supplier<BlockItem>) null);
    public static final RegistryObject<Block> FRIDGE_LIGHT = register("fridge_light", new FridgeBlock(Block.Properties.from(Blocks.IRON_BLOCK), () -> ModBlocks.FREEZER_LIGHT), block -> new BlockSupplierItem(new Item.Properties().group(FurnitureMod.GROUP), block, ModBlocks.FREEZER_LIGHT));
    public static final RegistryObject<Block> FREEZER_DARK = register("freezer_dark", new FreezerBlock(Block.Properties.from(Blocks.IRON_BLOCK), () -> ModBlocks.FRIDGE_DARK), (Supplier<BlockItem>) null);
    public static final RegistryObject<Block> FRIDGE_DARK = register("fridge_dark", new FridgeBlock(Block.Properties.from(Blocks.IRON_BLOCK), () -> ModBlocks.FREEZER_DARK), block -> new BlockSupplierItem(new Item.Properties().group(FurnitureMod.GROUP), block, ModBlocks.FREEZER_DARK));

    private static RegistryObject<Block> register(String name, Block block)
    {
        return register(name, block, new Item.Properties().group(FurnitureMod.GROUP));
    }

    private static RegistryObject<Block> register(String name, Block block, Item.Properties properties)
    {
        return register(name, block, () -> new BlockItem(block, properties));
    }

    private static RegistryObject<Block> register(String name, Block block, @Nullable Supplier<BlockItem> supplier)
    {
        if(supplier != null)
        {
            ModItems.REGISTER.register(name, supplier);
        }
        return REGISTER.register(name, () -> block);
    }

    private static RegistryObject<Block> register(String name, Block block, @Nullable Function<Block, BlockItem> function)
    {
        if(function != null)
        {
            ModItems.REGISTER.register(name, () -> function.apply(block));
        }
        return REGISTER.register(name, () -> block);
    }
}
