package com.mrcrayfish.furniture.init;

import com.mrcrayfish.furniture.blocks.*;
import com.mrcrayfish.furniture.items.*;
import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.item.ItemBlock;

public class FurnitureBlocks
{
    /* Initial Furniture */
    public static final Block COFFEE_TABLE_OAK, COFFEE_TABLE_STONE;
    public static final Block TABLE_OAK, TABLE_STONE;
    public static final Block CHAIR_OAK, CHAIR_STONE;
    public static final Block FREEZER, FRIDGE;
    public static final Block CABINET_OAK, BEDSIDE_CABINET_OAK;
    public static final Block COUCH, COUCH_JEB;
    public static final BlockBlinds BLINDS_OAK, BLINDS_OAK_CLOSED;
    public static final Block CURTAINS, CURTAINS_CLOSED;
    public static final Block OVEN, RANGE_HOOD, RANGE_HOOD_POWERED;

    /* Garden Update */
    public static final Block HEDGE_OAK, HEDGE_SPRUCE, HEDGE_BIRCH, HEDGE_JUNGLE, HEDGE_ACACIA, HEDGE_DARK_OAK;
    public static final Block BIRD_BATH, STONE_PATH, WHITE_FENCE, TAP, MAIL_BOX_OAK;

    /* Electronic Update */
    public static final Block TV, COMPUTER, PRINTER, ELECTRIC_FENCE, DOOR_BELL, STEREO;
    public static final Block FIRE_ALARM_OFF, FIRE_ALARM_ON;
    public static final Block CEILING_LIGHT_OFF, CEILING_LIGHT_ON;
    public static final Block LAMP_ON, LAMP_OFF;

    /* Bathroom Update */
    public static final Block TOILET, BASIN, BATH_1, BATH_2;
    public static final Block SHOWER_BOTTOM, SHOWER_TOP, SHOWER_HEAD_OFF, SHOWER_HEAD_ON;
    public static final Block WALL_CABINET;
    public static final Block BIN;

    /* Kitchen Update */
    public static final Block TOASTER, MICROWAVE, BLENDER, WASHING_MACHINE, DISHWASHER;
    public static final Block COUNTER, COUNTER_SINK, KITCHEN_CABINET;
    public static final Block CUP, PLATE, COOKIE_JAR, BAR_STOOL, CHOPPING_BOARD;

    /* Christmas Update */
    public static final Block PRESENT, TREE_BOTTOM, TREE_TOP;
    public static final Block MANTEL_PIECE, GRAND_CHAIR_TOP, GRAND_CHAIR_BOTTOM, CANDLE, CHIMNEY, WREATH, FAIRY_LIGHT, FIRE_PIT_OFF, FIRE_PIT_ON;

    /* Outdoor Update */
    public static final Block TRAMPOLINE, CRATE, BENCH, TABLE_OUTDOOR, GRILL, DIVING_BOARD_BASE, DIVING_BOARD_PLANK, DOOR_MAT, COOLER;
    public static final Block COFFEE_TABLE_SPRUCE, COFFEE_TABLE_BIRCH, COFFEE_TABLE_JUNGLE, COFFEE_TABLE_ACACIA, COFFEE_TABLE_DARK_OAK;
    public static final Block CHAIR_SPRUCE, CHAIR_BIRCH, CHAIR_JUNGLE, CHAIR_ACACIA, CHAIR_DARK_OAK;
    public static final Block TABLE_SPRUCE, TABLE_BIRCH, TABLE_JUNGLE, TABLE_ACACIA, TABLE_DARK_OAK;
    public static final Block CABINET_SPRUCE, CABINET_BIRCH, CABINET_JUNGLE, CABINET_ACACIA, CABINET_DARK_OAK;
    public static final Block BEDSIDE_CABINET_SPRUCE, BEDSIDE_CABINET_BIRCH, BEDSIDE_CABINET_JUNGLE, BEDSIDE_CABINET_ACACIA, BEDSIDE_CABINET_DARK_OAK;

    /* More Stone Furniture Update */
    public static final Block COFFEE_TABLE_GRANITE, COFFEE_TABLE_DIORITE, COFFEE_TABLE_ANDESITE;
    public static final Block TABLE_GRANITE, TABLE_DIORITE, TABLE_ANDESITE;
    public static final Block CHAIR_GRANITE, CHAIR_DIORITE, CHAIR_ANDESITE;

    /* The Modern Update */
    public static final Block BEDSIDE_CABINET_STONE, BEDSIDE_CABINET_GRANITE, BEDSIDE_CABINET_DIORITE, BEDSIDE_CABINET_ANDESITE;
    public static final Block MODERN_WINDOW, MODERN_SLIDING_DOOR, MODERN_TV, MODERN_COUCH, MODERN_TABLE, MODERN_CHAIR, MODERN_BED_TOP, MODERN_BED_BOTTOM, MODERN_COFFEE_TABLE, MODERN_STAIRS, MODERN_TABLE_OUTDOOR;
    public static final Block LIGHT_SWITCH_OFF, LIGHT_SWITCH_ON, MODERN_LIGHT_OFF, MODERN_LIGHT_ON;
    public static final Block CEILING_FAN;
    public static final Block DESK_OAK, DESK_SPRUCE, DESK_BIRCH, DESK_JUNGLE, DESK_ACACIA, DESK_DARK_OAK, DESK_STONE, DESK_GRANITE, DESK_DIORITE, DESK_ANDESITE;
    public static final Block DESK_CABINET_OAK, DESK_CABINET_SPRUCE, DESK_CABINET_BIRCH, DESK_CABINET_JUNGLE, DESK_CABINET_ACACIA, DESK_CABINET_DARK_OAK, DESK_CABINET_STONE, DESK_CABINET_GRANITE, DESK_CABINET_DIORITE, DESK_CABINET_ANDESITE;
    public static final Block CABINET_STONE, CABINET_GRANITE, CABINET_DIORITE, CABINET_ANDESITE;
    public static final Block DIGITAL_CLOCK;
    public static final Block COUNTER_DRAWER;
    public static final Block MAIL_BOX_SPRUCE, MAIL_BOX_BIRCH, MAIL_BOX_JUNGLE, MAIL_BOX_ACACIA, MAIL_BOX_DARK_OAK;
    public static final Block DOOR_BELL_SPRUCE, DOOR_BELL_BIRCH, DOOR_BELL_JUNGLE, DOOR_BELL_ACACIA, DOOR_BELL_DARK_OAK;
    public static final Block PHOTO_FRAME;
    public static final Block CRATE_SPRUCE, CRATE_BIRCH, CRATE_JUNGLE, CRATE_ACACIA, CRATE_DARK_OAK;
    public static final Block TV_STAND;
    public static final BlockBlinds BLINDS_SPRUCE, BLINDS_SPRUCE_CLOSED;
    public static final BlockBlinds BLINDS_BIRCH, BLINDS_BIRCH_CLOSED;
    public static final BlockBlinds BLINDS_JUNGLE, BLINDS_JUNGLE_CLOSED;
    public static final BlockBlinds BLINDS_ACACIA, BLINDS_ACACIA_CLOSED;
    public static final BlockBlinds BLINDS_DARK_OAK, BLINDS_DARK_OAK_CLOSED;

    /* The Outdoor Update V2 */
    public static final Block OAK_FENCE_UPGRADED, SPRUCE_FENCE_UPGRADED, BIRCH_FENCE_UPGRADED, JUNGLE_FENCE_UPGRADED, ACACIA_FENCE_UPGRADED, DARK_OAK_FENCE_UPGRADED, NETHER_BRICK_FENCE_UPGRADED;
    public static final Block OAK_GATE_UPGRADED, SPRUCE_GATE_UPGRADED, BIRCH_GATE_UPGRADED, JUNGLE_GATE_UPGRADED, ACACIA_GATE_UPGRADED, DARK_OAK_GATE_UPGRADED;
    public static final Block WHITE_GATE;

    /* Special */
    public static final Block MIRROR;

    static
    {
        COFFEE_TABLE_OAK = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_oak");
        COFFEE_TABLE_SPRUCE = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_spruce");
        COFFEE_TABLE_BIRCH = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_birch");
        COFFEE_TABLE_JUNGLE = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_jungle");
        COFFEE_TABLE_ACACIA = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_acacia");
        COFFEE_TABLE_DARK_OAK = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "coffee_table_dark_oak");
        COFFEE_TABLE_STONE = new BlockCoffeeTable(Material.ROCK, SoundType.STONE, "coffee_table_stone");
        TABLE_OAK = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_oak").setRegistryName("table_oak");
        TABLE_SPRUCE = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_spruce").setRegistryName("table_spruce");
        TABLE_BIRCH = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_birch").setRegistryName("table_birch");
        TABLE_JUNGLE = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_jungle").setRegistryName("table_jungle");
        TABLE_ACACIA = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_acacia").setRegistryName("table_acacia");
        TABLE_DARK_OAK = new BlockTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_dark_oak").setRegistryName("table_dark_oak");
        TABLE_STONE = new BlockTable(Material.ROCK, SoundType.STONE).setUnlocalizedName("table_stone").setRegistryName("table_stone");
        CHAIR_OAK = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_oak").setRegistryName("chair_oak");
        CHAIR_SPRUCE = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_spruce").setRegistryName("chair_spruce");
        CHAIR_BIRCH = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_birch").setRegistryName("chair_birch");
        CHAIR_JUNGLE = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_jungle").setRegistryName("chair_jungle");
        CHAIR_ACACIA = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_acacia").setRegistryName("chair_acacia");
        CHAIR_DARK_OAK = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("chair_dark_oak").setRegistryName("chair_dark_oak");
        CHAIR_STONE = new BlockChair(Material.ROCK, SoundType.STONE).setUnlocalizedName("chair_stone").setRegistryName("chair_stone");
        FREEZER = new BlockFreezer(Material.ROCK).setUnlocalizedName("freezer").setRegistryName("freezer");
        FRIDGE = new BlockFridge(Material.ROCK).setUnlocalizedName("fridge").setRegistryName("fridge");
        CABINET_OAK = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_oak").setRegistryName("cabinet_oak");
        CABINET_SPRUCE = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_spruce").setRegistryName("cabinet_spruce");
        CABINET_BIRCH = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_birch").setRegistryName("cabinet_birch");
        CABINET_JUNGLE = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_jungle").setRegistryName("cabinet_jungle");
        CABINET_ACACIA = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_acacia").setRegistryName("cabinet_acacia");
        CABINET_DARK_OAK = new BlockCabinet(Material.WOOD).setUnlocalizedName("cabinet_dark_oak").setRegistryName("cabinet_dark_oak");
        COUCH = new BlockCouchNormal().setUnlocalizedName("couch").setRegistryName("couch");
        COUCH_JEB = new BlockCouchJeb().setUnlocalizedName("couch_jeb").setRegistryName("couch_jeb");
        LAMP_ON = new BlockLampOn(Material.GLASS).setUnlocalizedName("lamp_on").setRegistryName("lamp_on");
        LAMP_OFF = new BlockLamp(Material.GLASS, false).setUnlocalizedName("lamp_off").setRegistryName("lamp_off");
        BLINDS_OAK = (BlockBlinds) new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_open").setRegistryName("blinds_open");
        BLINDS_OAK_CLOSED = (BlockBlinds) new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_closed").setRegistryName("blinds_closed");
        BLINDS_SPRUCE = (BlockBlinds) new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_spruce_open").setRegistryName("blinds_spruce_open");
        BLINDS_SPRUCE_CLOSED = (BlockBlinds) new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_spruce_closed").setRegistryName("blinds_spruce_closed");
        BLINDS_BIRCH = (BlockBlinds) new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_birch_open").setRegistryName("blinds_birch_open");
        BLINDS_BIRCH_CLOSED = (BlockBlinds) new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_birch_closed").setRegistryName("blinds_birch_closed");
        BLINDS_JUNGLE = (BlockBlinds) new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_jungle_open").setRegistryName("blinds_jungle_open");
        BLINDS_JUNGLE_CLOSED = (BlockBlinds) new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_jungle_closed").setRegistryName("blinds_jungle_closed");
        BLINDS_ACACIA = (BlockBlinds) new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_acacia_open").setRegistryName("blinds_acacia_open");
        BLINDS_ACACIA_CLOSED = (BlockBlinds) new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_acacia_closed").setRegistryName("blinds_acacia_closed");
        BLINDS_DARK_OAK = (BlockBlinds) new BlockBlinds(Material.WOOD, true).setUnlocalizedName("blinds_dark_oak_open").setRegistryName("blinds_dark_oak_open");
        BLINDS_DARK_OAK_CLOSED = (BlockBlinds) new BlockBlinds(Material.WOOD, false).setUnlocalizedName("blinds_dark_oak_closed").setRegistryName("blinds_dark_oak_closed");
        BLINDS_OAK.setReplacementBlock(BLINDS_OAK_CLOSED);
        BLINDS_OAK_CLOSED.setReplacementBlock(BLINDS_OAK);
        BLINDS_SPRUCE.setReplacementBlock(BLINDS_SPRUCE_CLOSED);
        BLINDS_SPRUCE_CLOSED.setReplacementBlock(BLINDS_SPRUCE);
        BLINDS_BIRCH.setReplacementBlock(BLINDS_BIRCH_CLOSED);
        BLINDS_BIRCH_CLOSED.setReplacementBlock(BLINDS_BIRCH);
        BLINDS_JUNGLE.setReplacementBlock(BLINDS_JUNGLE_CLOSED);
        BLINDS_JUNGLE_CLOSED.setReplacementBlock(BLINDS_JUNGLE);
        BLINDS_ACACIA.setReplacementBlock(BLINDS_ACACIA_CLOSED);
        BLINDS_ACACIA_CLOSED.setReplacementBlock(BLINDS_ACACIA);
        BLINDS_DARK_OAK.setReplacementBlock(BLINDS_DARK_OAK_CLOSED);
        BLINDS_DARK_OAK_CLOSED.setReplacementBlock(BLINDS_DARK_OAK);
        CURTAINS = new BlockCurtainsOpen(Material.CLOTH).setUnlocalizedName("curtains_open").setRegistryName("curtains_open");
        CURTAINS_CLOSED = new BlockCurtainsClosed(Material.CLOTH).setUnlocalizedName("curtains_closed").setRegistryName("curtains_closed");
        BEDSIDE_CABINET_OAK = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_oak").setRegistryName("bedside_cabinet_oak");
        BEDSIDE_CABINET_SPRUCE = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_spruce").setRegistryName("bedside_cabinet_spruce");
        BEDSIDE_CABINET_BIRCH = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_birch").setRegistryName("bedside_cabinet_birch");
        BEDSIDE_CABINET_JUNGLE = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_jungle").setRegistryName("bedside_cabinet_jungle");
        BEDSIDE_CABINET_ACACIA = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_acacia").setRegistryName("bedside_cabinet_acacia");
        BEDSIDE_CABINET_DARK_OAK = new BlockBedsideCabinet(Material.WOOD).setUnlocalizedName("bedside_cabinet_dark_oak").setRegistryName("bedside_cabinet_dark_oak");
        OVEN = new BlockOven(Material.ROCK).setUnlocalizedName("oven").setRegistryName("oven");
        RANGE_HOOD = new BlockRangeHood(Material.ROCK, false).setUnlocalizedName("range_hood").setRegistryName("range_hood");
        RANGE_HOOD_POWERED = new BlockRangeHood(Material.ROCK, true).setUnlocalizedName("range_hood_powered").setRegistryName("range_hood_powered");
        HEDGE_OAK = new BlockHedge().setUnlocalizedName("hedge_oak").setRegistryName("hedge_oak");
        HEDGE_SPRUCE = new BlockHedge().setUnlocalizedName("hedge_spruce").setRegistryName("hedge_spruce");
        HEDGE_BIRCH = new BlockHedge().setUnlocalizedName("hedge_birch").setRegistryName("hedge_birch");
        HEDGE_JUNGLE = new BlockHedge().setUnlocalizedName("hedge_jungle").setRegistryName("hedge_jungle");
        HEDGE_ACACIA = new BlockHedge().setUnlocalizedName("hedge_acacia").setRegistryName("hedge_acacia");
        HEDGE_DARK_OAK = new BlockHedge().setUnlocalizedName("hedge_dark_oak").setRegistryName("hedge_dark_oak");
        BIRD_BATH = new BlockBirdBath(Material.ROCK).setUnlocalizedName("bird_bath").setRegistryName("bird_bath");
        STONE_PATH = new BlockStonePath(Material.ROCK).setUnlocalizedName("stone_path").setRegistryName("stone_path");
        WHITE_FENCE = new BlockWhiteFence(Material.WOOD).setUnlocalizedName("white_fence").setRegistryName("white_fence");
        TAP = new BlockTap(Material.ROCK).setUnlocalizedName("tap").setRegistryName("tap");
        MAIL_BOX_OAK = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box").setRegistryName("mail_box");
        MAIL_BOX_SPRUCE = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_spruce").setRegistryName("mail_box_spruce");
        MAIL_BOX_BIRCH = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_birch").setRegistryName("mail_box_birch");
        MAIL_BOX_JUNGLE = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_jungle").setRegistryName("mail_box_jungle");
        MAIL_BOX_ACACIA = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_acacia").setRegistryName("mail_box_acacia");
        MAIL_BOX_DARK_OAK = new BlockMailBox(Material.WOOD).setUnlocalizedName("mail_box_dark_oak").setRegistryName("mail_box_dark_oak");
        TV = new BlockTV(Material.WOOD).setUnlocalizedName("tv").setRegistryName("tv");
        COMPUTER = new BlockComputer(Material.IRON).setUnlocalizedName("computer").setRegistryName("computer");
        PRINTER = new BlockPrinter(Material.IRON).setUnlocalizedName("printer").setRegistryName("printer");
        ELECTRIC_FENCE = new BlockElectricFence(Material.ROCK).setUnlocalizedName("electric_fence").setRegistryName("electric_fence");
        DOOR_BELL = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell").setRegistryName("door_bell");
        DOOR_BELL_SPRUCE = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_spruce").setRegistryName("door_bell_spruce");
        DOOR_BELL_BIRCH = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_birch").setRegistryName("door_bell_birch");
        DOOR_BELL_JUNGLE = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_jungle").setRegistryName("door_bell_jungle");
        DOOR_BELL_ACACIA = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_acacia").setRegistryName("door_bell_acacia");
        DOOR_BELL_DARK_OAK = new BlockDoorBell(Material.WOOD).setUnlocalizedName("door_bell_dark_oak").setRegistryName("door_bell_dark_oak");
        FIRE_ALARM_ON = new BlockFireAlarm(Material.ROCK, true).setUnlocalizedName("fire_alarm_on").setRegistryName("fire_alarm_on");
        FIRE_ALARM_OFF = new BlockFireAlarm(Material.ROCK, false).setUnlocalizedName("fire_alarm_off").setRegistryName("fire_alarm_off");
        CEILING_LIGHT_ON = new BlockCeilingLight(Material.GLASS, true).setUnlocalizedName("ceiling_light_on").setRegistryName("ceiling_light_on");
        CEILING_LIGHT_OFF = new BlockCeilingLight(Material.GLASS, false).setUnlocalizedName("ceiling_light_off").setRegistryName("ceiling_light_off");
        STEREO = new BlockStereo(Material.WOOD).setUnlocalizedName("stereo").setRegistryName("stereo");
        TOILET = new BlockToilet(Material.ROCK).setUnlocalizedName("toilet").setRegistryName("toilet");
        BASIN = new BlockBasin(Material.ROCK).setUnlocalizedName("basin").setRegistryName("basin");
        WALL_CABINET = new BlockWallCabinet(Material.ROCK).setUnlocalizedName("wall_cabinet").setRegistryName("wall_cabinet");
        BATH_1 = new BlockBath(Material.ROCK, false).setUnlocalizedName("bath_bottom").setRegistryName("bath_bottom");
        BATH_2 = new BlockBath(Material.ROCK, true).setUnlocalizedName("bath_top").setRegistryName("bath_top");
        SHOWER_BOTTOM = new BlockShower(Material.ROCK, false).setUnlocalizedName("shower_bottom").setRegistryName("shower_bottom");
        SHOWER_TOP = new BlockShower(Material.ROCK, true).setUnlocalizedName("shower_top").setRegistryName("shower_top");
        SHOWER_HEAD_OFF = new BlockShowerHeadOff(Material.ROCK).setUnlocalizedName("shower_head_off").setRegistryName("shower_head_off");
        SHOWER_HEAD_ON = new BlockShowerHeadOn(Material.ROCK).setUnlocalizedName("shower_head_on").setRegistryName("shower_head_on");
        BIN = new BlockBin(Material.ROCK).setUnlocalizedName("bin").setRegistryName("bin");
        TREE_TOP = new BlockTree(Material.WOOD, true).setUnlocalizedName("tree_top").setRegistryName("tree_top");
        TREE_BOTTOM = new BlockTree(Material.WOOD, false).setUnlocalizedName("tree_bottom").setRegistryName("tree_bottom");
        PRESENT = new BlockPresent(Material.CLOTH).setUnlocalizedName("present").setRegistryName("present");
        TOASTER = new BlockToaster(Material.WOOD).setUnlocalizedName("toaster").setRegistryName("toaster");
        MICROWAVE = new BlockMicrowave(Material.WOOD).setUnlocalizedName("microwave").setRegistryName("microwave");
        WASHING_MACHINE = new BlockWashingMachine(Material.ROCK).setUnlocalizedName("washing_machine").setRegistryName("washing_machine");
        COOKIE_JAR = new BlockCookieJar(Material.GLASS).setUnlocalizedName("cookie_jar").setRegistryName("cookie_jar");
        BLENDER = new BlockBlender(Material.GLASS).setUnlocalizedName("blender").setRegistryName("blender");
        CUP = new BlockCup(Material.GLASS).setUnlocalizedName("cup").setRegistryName("cup");
        PLATE = new BlockPlate(Material.GLASS).setUnlocalizedName("plate").setRegistryName("plate");
        COUNTER = new BlockCounter(Material.WOOD).setUnlocalizedName("counter").setRegistryName("counter");
        COUNTER_SINK = new BlockCounterSink(Material.WOOD).setUnlocalizedName("counter_sink").setRegistryName("counter_sink");
        COUNTER_DRAWER = new BlockCounterDrawer(Material.WOOD).setUnlocalizedName("counter_drawer").setRegistryName("counter_drawer");
        DISHWASHER = new BlockDishwasher(Material.ROCK).setUnlocalizedName("dishwasher").setRegistryName("dishwasher");
        KITCHEN_CABINET = new BlockCabinetKitchen(Material.WOOD).setUnlocalizedName("cabinet_kitchen").setRegistryName("cabinet_kitchen");
        CHOPPING_BOARD = new BlockChoppingBoard(Material.WOOD).setUnlocalizedName("chopping_board").setRegistryName("chopping_board");
        BAR_STOOL = new BlockBarStool(Material.WOOD).setUnlocalizedName("bar_stool").setRegistryName("bar_stool");
        MIRROR = new BlockMirror(Material.GLASS).setUnlocalizedName("mirror").setRegistryName("mirror");
        MANTEL_PIECE = new BlockMantelPiece(Material.ROCK).setUnlocalizedName("mantel_piece").setRegistryName("mantel_piece");
        GRAND_CHAIR_TOP = new BlockGrandChair(Material.WOOD, true).setUnlocalizedName("grand_chair_top").setRegistryName("grand_chair_top");
        GRAND_CHAIR_BOTTOM = new BlockGrandChair(Material.WOOD, false).setUnlocalizedName("grand_chair_bottom").setRegistryName("grand_chair_bottom");
        CANDLE = new BlockCandle(Material.ROCK).setUnlocalizedName("candle").setRegistryName("candle");
        CHIMNEY = new BlockChimney(Material.ROCK).setUnlocalizedName("chimney").setRegistryName("chimney");
        WREATH = new BlockWreath(Material.LEAVES).setUnlocalizedName("wreath").setRegistryName("wreath");
        FAIRY_LIGHT = new BlockFairyLight(Material.GLASS).setUnlocalizedName("fairy_light").setRegistryName("fairy_light");
        FIRE_PIT_OFF = new BlockFirePitOff(Material.WOOD).setUnlocalizedName("fire_pit_off").setRegistryName("fire_pit_off");
        FIRE_PIT_ON = new BlockFirePitOn(Material.WOOD).setUnlocalizedName("fire_pit_on").setRegistryName("fire_pit_on");
        TRAMPOLINE = new BlockTrampoline(Material.ROCK).setUnlocalizedName("trampoline").setRegistryName("trampoline");
        CRATE = new BlockCrate(Material.WOOD).setUnlocalizedName("crate").setRegistryName("crate");
        BENCH = new BlockBench(Material.WOOD).setUnlocalizedName("bench").setRegistryName("bench");
        TABLE_OUTDOOR = new BlockOutdoorTable(Material.WOOD, SoundType.WOOD).setUnlocalizedName("table_outdoor").setRegistryName("table_outdoor");
        GRILL = new BlockGrill(Material.ANVIL).setUnlocalizedName("grill").setRegistryName("grill");
        DIVING_BOARD_BASE = new BlockDivingboard(Material.ROCK, false).setUnlocalizedName("divingboard_base").setRegistryName("divingboard_base");
        DIVING_BOARD_PLANK = new BlockDivingboard(Material.ROCK, true).setUnlocalizedName("divingboard_plank").setRegistryName("divingboard_plank");
        DOOR_MAT = new BlockDoorMat(Material.CLOTH).setUnlocalizedName("door_mat").setRegistryName("door_mat");
        COOLER = new BlockEsky(Material.CLAY).setUnlocalizedName("esky").setRegistryName("esky");
        COFFEE_TABLE_GRANITE = new BlockCoffeeTable(Material.ROCK, SoundType.STONE, "coffee_table_granite");
        COFFEE_TABLE_DIORITE = new BlockCoffeeTable(Material.ROCK, SoundType.STONE, "coffee_table_diorite");
        COFFEE_TABLE_ANDESITE = new BlockCoffeeTable(Material.ROCK, SoundType.STONE, "coffee_table_andesite");
        TABLE_GRANITE = new BlockTable(Material.ROCK, SoundType.STONE).setUnlocalizedName("table_granite").setRegistryName("table_granite");
        TABLE_DIORITE = new BlockTable(Material.ROCK, SoundType.STONE).setUnlocalizedName("table_diorite").setRegistryName("table_diorite");
        TABLE_ANDESITE = new BlockTable(Material.ROCK, SoundType.STONE).setUnlocalizedName("table_andesite").setRegistryName("table_andesite");
        CHAIR_GRANITE = new BlockChair(Material.ROCK, SoundType.STONE).setUnlocalizedName("chair_granite").setRegistryName("chair_granite");
        CHAIR_DIORITE = new BlockChair(Material.ROCK, SoundType.STONE).setUnlocalizedName("chair_diorite").setRegistryName("chair_diorite");
        CHAIR_ANDESITE = new BlockChair(Material.ROCK, SoundType.STONE).setUnlocalizedName("chair_andesite").setRegistryName("chair_andesite");
        BEDSIDE_CABINET_STONE = new BlockBedsideCabinet(Material.ROCK).setUnlocalizedName("bedside_cabinet_stone").setRegistryName("bedside_cabinet_stone");
        BEDSIDE_CABINET_GRANITE = new BlockBedsideCabinet(Material.ROCK).setUnlocalizedName("bedside_cabinet_granite").setRegistryName("bedside_cabinet_granite");
        BEDSIDE_CABINET_DIORITE = new BlockBedsideCabinet(Material.ROCK).setUnlocalizedName("bedside_cabinet_diorite").setRegistryName("bedside_cabinet_diorite");
        BEDSIDE_CABINET_ANDESITE = new BlockBedsideCabinet(Material.ROCK).setUnlocalizedName("bedside_cabinet_andesite").setRegistryName("bedside_cabinet_andesite");
        MODERN_WINDOW = new BlockModernWindow().setUnlocalizedName("modern_window").setRegistryName("modern_window");
        MODERN_SLIDING_DOOR = new BlockModernSlidingDoor().setUnlocalizedName("modern_sliding_door").setRegistryName("modern_sliding_door");
        LIGHT_SWITCH_OFF = new BlockLightSwitch().setUnlocalizedName("light_switch_off").setRegistryName("light_switch_off");
        LIGHT_SWITCH_ON = new BlockLightSwitch().setUnlocalizedName("light_switch_on").setRegistryName("light_switch_on");
        CEILING_FAN = new BlockCeilingFan().setUnlocalizedName("ceiling_fan").setRegistryName("ceiling_fan");
        DESK_OAK = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_oak").setRegistryName("desk_oak");
        DESK_SPRUCE = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_spruce").setRegistryName("desk_spruce");
        DESK_BIRCH = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_birch").setRegistryName("desk_birch");
        DESK_JUNGLE = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_jungle").setRegistryName("desk_jungle");
        DESK_ACACIA = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_acacia").setRegistryName("desk_acacia");
        DESK_DARK_OAK = new BlockDesk(Material.WOOD).setUnlocalizedName("desk_dark_oak").setRegistryName("desk_dark_oak");
        DESK_STONE = new BlockDesk(Material.ROCK).setUnlocalizedName("desk_stone").setRegistryName("desk_stone");
        DESK_GRANITE = new BlockDesk(Material.ROCK).setUnlocalizedName("desk_granite").setRegistryName("desk_granite");
        DESK_DIORITE = new BlockDesk(Material.ROCK).setUnlocalizedName("desk_diorite").setRegistryName("desk_diorite");
        DESK_ANDESITE = new BlockDesk(Material.ROCK).setUnlocalizedName("desk_andesite").setRegistryName("desk_andesite");
        DESK_CABINET_OAK = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_oak").setRegistryName("desk_cabinet_oak");
        DESK_CABINET_SPRUCE = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_spruce").setRegistryName("desk_cabinet_spruce");
        DESK_CABINET_BIRCH = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_birch").setRegistryName("desk_cabinet_birch");
        DESK_CABINET_JUNGLE = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_jungle").setRegistryName("desk_cabinet_jungle");
        DESK_CABINET_ACACIA = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_acacia").setRegistryName("desk_cabinet_acacia");
        DESK_CABINET_DARK_OAK = new BlockDeskCabinet(Material.WOOD).setUnlocalizedName("desk_cabinet_dark_oak").setRegistryName("desk_cabinet_dark_oak");
        DESK_CABINET_STONE = new BlockDeskCabinet(Material.ROCK).setUnlocalizedName("desk_cabinet_stone").setRegistryName("desk_cabinet_stone");
        DESK_CABINET_GRANITE = new BlockDeskCabinet(Material.ROCK).setUnlocalizedName("desk_cabinet_granite").setRegistryName("desk_cabinet_granite");
        DESK_CABINET_DIORITE = new BlockDeskCabinet(Material.ROCK).setUnlocalizedName("desk_cabinet_diorite").setRegistryName("desk_cabinet_diorite");
        DESK_CABINET_ANDESITE = new BlockDeskCabinet(Material.ROCK).setUnlocalizedName("desk_cabinet_andesite").setRegistryName("desk_cabinet_andesite");
        CABINET_STONE = new BlockCabinet(Material.ROCK).setUnlocalizedName("cabinet_stone").setRegistryName("cabinet_stone");
        CABINET_GRANITE = new BlockCabinet(Material.ROCK).setUnlocalizedName("cabinet_granite").setRegistryName("cabinet_granite");
        CABINET_DIORITE = new BlockCabinet(Material.ROCK).setUnlocalizedName("cabinet_diorite").setRegistryName("cabinet_diorite");
        CABINET_ANDESITE = new BlockCabinet(Material.ROCK).setUnlocalizedName("cabinet_andesite").setRegistryName("cabinet_andesite");
        DIGITAL_CLOCK = new BlockDigitalClock();
        MODERN_TV = new BlockModernTV();
        PHOTO_FRAME = new BlockPhotoFrame();
        MODERN_COUCH = new BlockModernCouch();
        MODERN_TABLE = new BlockModernTable("modern_table");
        MODERN_CHAIR = new BlockChair(Material.WOOD, SoundType.WOOD).setUnlocalizedName("modern_chair").setRegistryName("modern_chair");
        CRATE_SPRUCE = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_spruce").setRegistryName("crate_spruce");
        CRATE_BIRCH = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_birch").setRegistryName("crate_birch");
        CRATE_JUNGLE = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_jungle").setRegistryName("crate_jungle");
        CRATE_ACACIA = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_acacia").setRegistryName("crate_acacia");
        CRATE_DARK_OAK = new BlockCrate(Material.WOOD).setUnlocalizedName("crate_dark_oak").setRegistryName("crate_dark_oak");
        MODERN_BED_TOP = new BlockModernBed("modern_bed_top");
        MODERN_BED_BOTTOM = new BlockModernBed("modern_bed_bottom");
        TV_STAND = new BlockTVStand();
        MODERN_COFFEE_TABLE = new BlockCoffeeTable(Material.WOOD, SoundType.WOOD, "modern_coffee_table");
        MODERN_STAIRS = new BlockModernStair();
        MODERN_TABLE_OUTDOOR = new BlockModernTable("modern_table_outdoor");
        MODERN_LIGHT_OFF = new BlockModernLight("modern_light_off", false);
        MODERN_LIGHT_ON = new BlockModernLight("modern_light_on", true);
        OAK_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_oak");
        SPRUCE_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_spruce");
        BIRCH_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_birch");
        JUNGLE_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_jungle");
        ACACIA_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_acacia");
        DARK_OAK_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_dark_oak");
        NETHER_BRICK_FENCE_UPGRADED = new BlockUpgradedFence("upgraded_fence_nether_brick");
        OAK_GATE_UPGRADED = new BlockUpgradedGate("upgraded_gate_oak");
        SPRUCE_GATE_UPGRADED = new BlockUpgradedGate("upgraded_gate_spruce");
        BIRCH_GATE_UPGRADED = new BlockUpgradedGate("upgraded_gate_birch");
        JUNGLE_GATE_UPGRADED = new BlockUpgradedGate("upgraded_gate_jungle");
        ACACIA_GATE_UPGRADED = new BlockUpgradedGate("upgraded_gate_acacia");
        DARK_OAK_GATE_UPGRADED = new BlockUpgradedGate("upgraded_gate_dark_oak");
        WHITE_GATE = new BlockWhiteGate("white_gate");
    }

    public static void register()
    {
        registerBlock(COFFEE_TABLE_OAK);
        registerBlock(COFFEE_TABLE_SPRUCE);
        registerBlock(COFFEE_TABLE_BIRCH);
        registerBlock(COFFEE_TABLE_JUNGLE);
        registerBlock(COFFEE_TABLE_ACACIA);
        registerBlock(COFFEE_TABLE_DARK_OAK);
        registerBlock(COFFEE_TABLE_STONE);
        registerBlock(COFFEE_TABLE_GRANITE);
        registerBlock(COFFEE_TABLE_DIORITE);
        registerBlock(COFFEE_TABLE_ANDESITE);
        registerBlock(TABLE_OAK);
        registerBlock(TABLE_SPRUCE);
        registerBlock(TABLE_BIRCH);
        registerBlock(TABLE_JUNGLE);
        registerBlock(TABLE_ACACIA);
        registerBlock(TABLE_DARK_OAK);
        registerBlock(TABLE_STONE);
        registerBlock(TABLE_GRANITE);
        registerBlock(TABLE_DIORITE);
        registerBlock(TABLE_ANDESITE);
        registerBlock(CHAIR_OAK);
        registerBlock(CHAIR_SPRUCE);
        registerBlock(CHAIR_BIRCH);
        registerBlock(CHAIR_JUNGLE);
        registerBlock(CHAIR_ACACIA);
        registerBlock(CHAIR_DARK_OAK);
        registerBlock(CHAIR_STONE);
        registerBlock(CHAIR_GRANITE);
        registerBlock(CHAIR_DIORITE);
        registerBlock(CHAIR_ANDESITE);
        registerBlock(FREEZER);
        registerBlock(FRIDGE, null);
        registerBlock(CABINET_OAK);
        registerBlock(CABINET_SPRUCE);
        registerBlock(CABINET_BIRCH);
        registerBlock(CABINET_JUNGLE);
        registerBlock(CABINET_ACACIA);
        registerBlock(CABINET_DARK_OAK);
        registerBlock(CABINET_STONE);
        registerBlock(CABINET_GRANITE);
        registerBlock(CABINET_DIORITE);
        registerBlock(CABINET_ANDESITE);
        registerBlock(COUCH, new ItemBlockColored(COUCH));
        registerBlock(COUCH_JEB);
        registerBlock(LAMP_ON, null);
        registerBlock(LAMP_OFF, new ItemBlockColored(LAMP_OFF));
        registerBlock(BLINDS_OAK);
        registerBlock(BLINDS_OAK_CLOSED, null);
        registerBlock(BLINDS_SPRUCE);
        registerBlock(BLINDS_SPRUCE_CLOSED, null);
        registerBlock(BLINDS_BIRCH);
        registerBlock(BLINDS_BIRCH_CLOSED, null);
        registerBlock(BLINDS_JUNGLE);
        registerBlock(BLINDS_JUNGLE_CLOSED, null);
        registerBlock(BLINDS_ACACIA);
        registerBlock(BLINDS_ACACIA_CLOSED, null);
        registerBlock(BLINDS_DARK_OAK);
        registerBlock(BLINDS_DARK_OAK_CLOSED, null);
        registerBlock(CURTAINS, new ItemColoredFurniture(CURTAINS));
        registerBlock(CURTAINS_CLOSED, null);
        registerBlock(BEDSIDE_CABINET_OAK);
        registerBlock(BEDSIDE_CABINET_SPRUCE);
        registerBlock(BEDSIDE_CABINET_BIRCH);
        registerBlock(BEDSIDE_CABINET_JUNGLE);
        registerBlock(BEDSIDE_CABINET_ACACIA);
        registerBlock(BEDSIDE_CABINET_DARK_OAK);
        registerBlock(BEDSIDE_CABINET_STONE);
        registerBlock(BEDSIDE_CABINET_GRANITE);
        registerBlock(BEDSIDE_CABINET_DIORITE);
        registerBlock(BEDSIDE_CABINET_ANDESITE);
        registerBlock(OVEN);
        registerBlock(RANGE_HOOD);
        registerBlock(RANGE_HOOD_POWERED, null);
        registerBlock(HEDGE_OAK, new ItemHedge(HEDGE_OAK));
        registerBlock(HEDGE_SPRUCE, new ItemHedge(HEDGE_SPRUCE));
        registerBlock(HEDGE_BIRCH, new ItemHedge(HEDGE_BIRCH));
        registerBlock(HEDGE_JUNGLE, new ItemHedge(HEDGE_JUNGLE));
        registerBlock(HEDGE_ACACIA, new ItemHedge(HEDGE_ACACIA));
        registerBlock(HEDGE_DARK_OAK, new ItemHedge(HEDGE_DARK_OAK));
        registerBlock(BIRD_BATH);
        registerBlock(STONE_PATH);
        registerBlock(WHITE_FENCE);
        registerBlock(WHITE_GATE, new ItemUpgradedGate(WHITE_GATE));
        registerBlock(TAP);
        registerBlock(MAIL_BOX_OAK);
        registerBlock(MAIL_BOX_SPRUCE);
        registerBlock(MAIL_BOX_BIRCH);
        registerBlock(MAIL_BOX_JUNGLE);
        registerBlock(MAIL_BOX_ACACIA);
        registerBlock(MAIL_BOX_DARK_OAK);
        registerBlock(TV);
        registerBlock(COMPUTER);
        registerBlock(PRINTER);
        registerBlock(ELECTRIC_FENCE);
        registerBlock(DOOR_BELL);
        registerBlock(DOOR_BELL_SPRUCE);
        registerBlock(DOOR_BELL_BIRCH);
        registerBlock(DOOR_BELL_JUNGLE);
        registerBlock(DOOR_BELL_ACACIA);
        registerBlock(DOOR_BELL_DARK_OAK);
        registerBlock(FIRE_ALARM_OFF);
        registerBlock(FIRE_ALARM_ON);
        registerBlock(CEILING_LIGHT_OFF);
        registerBlock(CEILING_LIGHT_ON, null);
        registerBlock(STEREO);
        registerBlock(TOILET);
        registerBlock(BASIN);
        registerBlock(WALL_CABINET);
        registerBlock(BATH_1, new ItemBath(BATH_1));
        registerBlock(BATH_2, null);
        registerBlock(SHOWER_BOTTOM);
        registerBlock(SHOWER_TOP, null);
        registerBlock(SHOWER_HEAD_OFF);
        registerBlock(SHOWER_HEAD_ON, null);
        registerBlock(BIN);
        registerBlock(PRESENT, new ItemPresent(PRESENT));
        registerBlock(TREE_TOP, null);
        registerBlock(TREE_BOTTOM, new ItemWreath(TREE_BOTTOM));
        registerBlock(TOASTER);
        registerBlock(MICROWAVE);
        registerBlock(WASHING_MACHINE);
        registerBlock(COOKIE_JAR);
        registerBlock(BLENDER);
        registerBlock(CUP, null);
        registerBlock(PLATE);
        registerBlock(COUNTER, new ItemBlockColored(COUNTER));
        registerBlock(COUNTER_SINK, new ItemBlockColored(COUNTER_SINK));
        registerBlock(COUNTER_DRAWER, new ItemBlockColored(COUNTER_DRAWER));
        registerBlock(DISHWASHER);
        registerBlock(KITCHEN_CABINET, new ItemBlockColored(KITCHEN_CABINET));
        registerBlock(CHOPPING_BOARD);
        registerBlock(BAR_STOOL, new ItemBlockColored(BAR_STOOL));
        registerBlock(MIRROR);
        registerBlock(MANTEL_PIECE);
        registerBlock(GRAND_CHAIR_TOP, null);
        registerBlock(GRAND_CHAIR_BOTTOM);
        registerBlock(CANDLE);
        registerBlock(CHIMNEY);
        registerBlock(WREATH, new ItemWreath(WREATH));
        registerBlock(FAIRY_LIGHT);
        registerBlock(FIRE_PIT_OFF, null);
        registerBlock(FIRE_PIT_ON);
        registerBlock(TRAMPOLINE);
        registerBlock(CRATE, new ItemCrate(CRATE));
        registerBlock(CRATE_SPRUCE, new ItemCrate(CRATE_SPRUCE));
        registerBlock(CRATE_BIRCH, new ItemCrate(CRATE_BIRCH));
        registerBlock(CRATE_JUNGLE, new ItemCrate(CRATE_JUNGLE));
        registerBlock(CRATE_ACACIA, new ItemCrate(CRATE_ACACIA));
        registerBlock(CRATE_DARK_OAK, new ItemCrate(CRATE_DARK_OAK));
        registerBlock(BENCH);
        registerBlock(TABLE_OUTDOOR);
        registerBlock(GRILL);
        registerBlock(DIVING_BOARD_BASE, new ItemBath(DIVING_BOARD_BASE));
        registerBlock(DIVING_BOARD_PLANK, null);
        registerBlock(DOOR_MAT, new ItemBlockColored(DOOR_MAT));
        registerBlock(COOLER, new ItemBlockColored(COOLER));
        registerBlock(MODERN_WINDOW);
        registerBlock(MODERN_SLIDING_DOOR, new ItemModernSlidingDoor(MODERN_SLIDING_DOOR));
        registerBlock(LIGHT_SWITCH_OFF, new ItemLightSwitch(LIGHT_SWITCH_OFF));
        registerBlock(LIGHT_SWITCH_ON, null);
        registerBlock(CEILING_FAN);
        registerBlock(DESK_OAK);
        registerBlock(DESK_SPRUCE);
        registerBlock(DESK_BIRCH);
        registerBlock(DESK_JUNGLE);
        registerBlock(DESK_ACACIA);
        registerBlock(DESK_DARK_OAK);
        registerBlock(DESK_STONE);
        registerBlock(DESK_GRANITE);
        registerBlock(DESK_DIORITE);
        registerBlock(DESK_ANDESITE);
        registerBlock(DESK_CABINET_OAK);
        registerBlock(DESK_CABINET_SPRUCE);
        registerBlock(DESK_CABINET_BIRCH);
        registerBlock(DESK_CABINET_JUNGLE);
        registerBlock(DESK_CABINET_ACACIA);
        registerBlock(DESK_CABINET_DARK_OAK);
        registerBlock(DESK_CABINET_STONE);
        registerBlock(DESK_CABINET_GRANITE);
        registerBlock(DESK_CABINET_DIORITE);
        registerBlock(DESK_CABINET_ANDESITE);
        registerBlock(DIGITAL_CLOCK, new ItemColored(DIGITAL_CLOCK));
        registerBlock(MODERN_TV);
        registerBlock(PHOTO_FRAME, new ItemColoredFurniture(PHOTO_FRAME));
        registerBlock(MODERN_COUCH, new ItemColoredFurniture(MODERN_COUCH));
        registerBlock(MODERN_TABLE);
        registerBlock(MODERN_CHAIR);
        registerBlock(MODERN_COFFEE_TABLE);
        registerBlock(MODERN_TABLE_OUTDOOR);
        registerBlock(MODERN_STAIRS);
        registerBlock(MODERN_BED_TOP, null);
        registerBlock(MODERN_BED_BOTTOM, new ItemModernBed());
        registerBlock(TV_STAND);
        registerBlock(MODERN_LIGHT_OFF);
        registerBlock(MODERN_LIGHT_ON, null);
        registerBlock(OAK_FENCE_UPGRADED);
        registerBlock(SPRUCE_FENCE_UPGRADED);
        registerBlock(BIRCH_FENCE_UPGRADED);
        registerBlock(JUNGLE_FENCE_UPGRADED);
        registerBlock(ACACIA_FENCE_UPGRADED);
        registerBlock(DARK_OAK_FENCE_UPGRADED);
        registerBlock(NETHER_BRICK_FENCE_UPGRADED);
        registerBlock(OAK_GATE_UPGRADED, new ItemUpgradedGate(OAK_GATE_UPGRADED));
        registerBlock(SPRUCE_GATE_UPGRADED, new ItemUpgradedGate(SPRUCE_GATE_UPGRADED));
        registerBlock(BIRCH_GATE_UPGRADED, new ItemUpgradedGate(BIRCH_GATE_UPGRADED));
        registerBlock(JUNGLE_GATE_UPGRADED, new ItemUpgradedGate(JUNGLE_GATE_UPGRADED));
        registerBlock(ACACIA_GATE_UPGRADED, new ItemUpgradedGate(ACACIA_GATE_UPGRADED));
        registerBlock(DARK_OAK_GATE_UPGRADED, new ItemUpgradedGate(DARK_OAK_GATE_UPGRADED));
    }

    private static void registerBlock(Block block)
    {
        registerBlock(block, new ItemBlock(block));
    }

    private static void registerBlock(Block block, ItemBlock item)
    {
        if(block.getRegistryName() == null)
            throw new IllegalArgumentException("A block being registered does not have a registry name and could be successfully registered.");

        RegistrationHandler.Blocks.add(block);

        if(item != null)
        {
            item.setRegistryName(block.getRegistryName());
            RegistrationHandler.Items.add(item);
        }
    }
}
